### ISSUE TITLE
2. 네트워크와 케이블, 그리고 친구들

### ISSUE THREAD

**Issue by hhhyunwoo** [WhiteKow/hoony-easy-written-cisco-networking-study#1]

**Comment by jjangsungwon** [comment]
### **LAN(Local Area Network)이란?**
- 어느 한정된 공간에서 네트워크를 구성하는 것
- WAN(Wide Area Network): 멀리 떨어진 곳과의 네트워크 구성

### **이더넷이란?**
- 네트워킹 방식
- CSMA/CD(Carrier Sense Multiple Access/Collision Detection) 프로토콜을 사용해서 통신
  - CSMA: 대충 알아서 눈치로 통신. 아무도 통신을 하고 있지 않으면 자기 데이터를 실어서 보낸 후 잘 갔는지 확인. 만약 동시에 2개의 컴퓨터에서 데이터를 실어 보내면(다중 접근) 충돌이 발생(콜리전)하게 되는데 이런 경우 자신이 보내려던 데이터를 랜덤한 시간 동안 기다렸다가 다시 보냄. 또 충돌이 일어나면 다시 랜덤한 시간 기다리고 반복

### **토큰링이란?**
- 오직 한 PC, 즉 토큰을 가진 PC만이 네트워크에 데이터를 실어 보낼 수 있는 네트워킹 방식
- 이더넷보다 안정된 기술이라는 주장이 나오면서 인기를 끌던 시절이 있었지만 속도가 너무 느려서 역사의 뒤안길로 사라짐

### **케이블이란?**
- 케이블은 장비와 장비의 연결 어디에나 들어감
- UTP(Unshielded Twisted-pair) 케이블로 주로 구성됨
- 케이블의 속도가 빨라지면 빨라질수록 전송 거리는 점점 짧아지

### **맥 어드레스(MAC Address)**
- 통신을 위해서 필요한 주소
- 48비트로 구성
- 앞쪽의 절반은 네트워크 장비를 만드는 회사 정보, 나머지 절반은 시리얼 번호

### **유니캐스트, 브로드캐스트, 멀티캐스트**
- 유니캐스트: 1대1로 하는 통신 방식
- 브로드캐스트: 전부를 대상을 하는 통신 방식
- 멀티캐스트: 어떤 그룹을 대상으로 하는 통신 방식

### **OSI 7 계층**
- 통신을 7개의 단계별로 표준화하여 효율성을 높이기 위해 사용된 것
- 데이터의 흐름이 한눈에 보인다.
- 문제를 해결하기가 편리하다.
- 여러 회사 장비를 써도 네트워크가 이상 없이 돌아간다.

**Comment by ChanhuiSeok** [comment]
## 2장
- LAN 은 Local Area Network, WAN 은 Wide Area Network. 한정된 지역 안에서의 네트워크 구축 vs 서로 멀리 떨어진 곳을 네트워크로 연결
- 이더넷
    - 네트워킹의 한 방식으로, 네트워크를 만드는 방법 중 하나
    - CSMA/CD라는 프로토콜 사용 (한 마디로 말하면 대충 알아서 눈치로 통신하자!)
        - 통신하고자 하는 컴퓨터가 네트워크를 살펴보고 아무도 통신을 하고 있지 않으면, 무조건 자기 데이터를 실어보낸 후 잘 갔는지 확인해 보는 방식. 그런데 2개의 컴퓨터가 동시에 데이터를 실어 보내려 하면 **콜리전**이 발생한다. 이 두 PC는 자신이 보내려던 데이터를 랜덤한 시간 동안 기다렸다가 다시 보내게 된다.
- 토큰링
    - 이더넷과 달리, 그 네트워크에서 오직 한 PC, 즉 토큰을 가진 PC만이 네트워크에 데이터를 실어 보낼 수 있는 방식
    - 콜리전(충돌)이 발생하지 않음 (옆으로 전달하는 방식의 통신이므로)
    - 따라서 네트워크 성능 예측도 쉬움
    - 단점 > 내가 지금 바로 보내야 할 데이터가 있고, 다른 PC들은 보낼 데이터가 없어도 내 차례가 올 때까지 기다려야 함, 이더넷의 눈부신 발전으로 토큰링은 역사의 뒤안길로 사라짐
- UTP 케이블
    - TP는 Twisted-pair, 꼬인 녀석이라는 의미이다. U는 Unshielded, 절연체로 감싸있지 않은 것이다.
    - 카테고리가 나뉜다. 주로 카테고리 5(Cat5) 부터 100Mbps 이상 지원이 된다. 10Gbps는 최소한 Cat6(Cat6a) 이상을 써야 한다.
- 맥 어드레스  (MAC은 Media Access Control의 줄임말)
    - **컴퓨터가 네트워크상에서 어떻게 서로를 구분할지, 일종의 주소가 필요한데 그 역할을 한다.**
    - 각 장비마다 IP 주소가 배정되고 그 주소로 통신하지만 이 경우에도 맥 어드레스를 사용한다.
    - **IP 주소를 다시 MAC으로 바꾸는 절차를** ARP(Address Resolution Protocol)라고 한다.
    - 네트워크에 붙는 각 장비들은 48비트의 주소를 가진다. **이 주소는 랜카드 혹은 네트워크 장비에 이미 고정된 (전 세계에서 유일한) 주소이다.** 이것을 맥 어드레스나 하드웨어 주소라고 한다. 모든 랜의 디바이스들은 반드시 유일한 맥 어드레스를 가져야 한다. 라우터나 스위치에도 맥 어드레스가 들어 있다.
    - 이 맥 주소에 보면 앞쪽 6개의 16진수는 생산자를 나타내는 코드(OUI) 이다. 메이커마다 달라서 어느 회사에서 만든 제품인지 알 수 있다. 그리고 그 뒤 나머지 6자리 수가 시리얼 넘버인 셈이다.
    - 즉, 맥 주소 중에서 앞쪽 절반은 미리 약속된 규정에 따라 네트워크 장비 회사에 분배하고, 그 회사에서 나머지 절반을 일련번호로 만들어 각 장비에 부여한다.
- 유니캐스트, 멀티캐스트, 브로드캐스트
    - 유니캐스트 : 특정 목적지의 주소 하나만을 가지고 통신하는 방식이다. 정확하게 받는 PC의 맥 주소를 프레임 안에 써넣는다. 이 때 PC는 한 개이다. 어떤 PC가 유니캐스트 프레임을 뿌리면, 로컬 네트워크상의 모든 PC들이 일단 이 프레임으로부터 자신의 맥 어드레스와 비교한다. 다르면 바로 그 프레임을 버리고, 같으면 통신 시작. 그러므로 다른 PC들의 CPU 성능을 저하시키지 않는다.
    - 브로드캐스트 : 로컬 랜에 붙어 있는 모든 네트워크 장비들에게 보내는 통신이다. 내가 살고 있는 모든 네트워크 장비들에 통신할 때 쓰기 위한 방식이다. 받기 싫다고 해서 받지 않는게 아니라 모두가 그대로 받는다. 브로드캐스트의 맥주소는 FFFF.FFFF.FFFF로 미리 정해져 있다.
    과도한 브로드캐스트는 성능을 하락시키는 원인이 된다. (전체 트래픽 증가, 패킷 받은 모든 랜카드가 이 패킷을 CPU로 전송하므로)
        - 처음 두 PC간 통신을 하는 경우, 상대편 IP 주소는 알아도 MAC 주소는 모르므로 알아내기 위해 하는 동작이 ARP이며, **ARP가 브로드캐스트**이다.
        - 라우터끼리 정보 교환하거나, 서버들이 서비스 제공 여부를 모든 클라이언트들에게 알릴 때 등 여러 경우에서도 사용한다.
    - 멀티캐스트 : 보내고자 하는 그룹 멤버들에게만 한 번에 보낼 수 있음. 받기 싫어하는 사람에게까지 보낼 필요가 없다. 유니캐스트처럼 전부 하나씩 여러 번 보낼 필요도 없다. 즉, 특정 그룹 데이터를 보낼 때 적당한 방법으로 유니캐스트와 브로드캐스트의 장점을 결합해, 한 번에 그룹 멤버들에게 다 보내면서도 그 이외의 PC에는 영향을 주지 않는다는 특징을 가진다. 단, 스위치나 라우터가 멀티캐스트 기능을 꼭 지원해야 한다는 제약이 있다.
- OSI 7계층
    - 통신이 일어나는 과정을 7개의 단계로 나누었다. 통신을 단계별로 표준화해서 효율성을 높이고자 사용된다.
    - 나눈 이유?
        - 데이터의 흐름이 한눈에 보인다.
        - 문제를 해결하기 편리하다. 네트워크에 문제가 발생하면, 이 문제 하나를 7개의 작은 문제로 나누고 그 문제를 해결하면 훨씬 쉽다. 즉 어느 단계에서 문제가 생겼는지 파악하는 과정에서 특정 계층까지는 문제가 없다는 결론을 내릴 수 있다.
        - 이렇게 표준화를 하니까, 여러 회사 장비를 써도 네트워크가 이상 없이 돌아간다.

**Comment by hhhyunwoo** [comment]
# 2. 네트워크와 케이블, 그리고 친구들

# LAN vs WAN

![image](https://user-images.githubusercontent.com/37402136/205407866-0cf6dd01-3cc0-441d-9f54-2470bc3734cc.png)

- LAN
    - 어느 한정된 공간에서 네트워크를 구성
- WAN
    - 멀리 떨어진 지역을 서로 연결하는 경우

# Ethernet

- 이더넷은 네트워킹의 한 방식
- 이더넷의 가장 큰 특징은 CSMA/CD 라는 프로토콜을 사용해서 통신한다는 것
- 우리나라에서 사용하는 대부분의 네트워킹 방식이 이더넷임

![image](https://user-images.githubusercontent.com/37402136/205407907-f24dc490-af14-4723-8138-c721a8f7027d.png)

## CSMA/CD

- Carrier Sencse Multiple Access / Collision Detection
    - 눈치게임!
    - 누군가가 네트워크 상에서 통신을 하고 있으면 자기가 보낼 정보가 있어도 못보내고 기다림
- Carrier
    - 네트워크 상에 나타나는 신호
- Multiple Access
    - 동시에 2개 이상의 장비에서 통신을 해버리면 Collision이 발생
    - 그렇게 되면 PC 들은 랜덤한 시간동안 기다렸다가 데이터 다시 전송

# TokenRing

- 오직 한 PC가 네트워크에 데이터를 실어 보낼 수 있음
- Collision 발생하지 않음.
- 네트워크 성능 예측도 쉬움.

# UTP 케이블

- TP
    - Twisted-pair
- UTP
    - Unshielded
- STP
    - Shielded
    - 더 비싸고 성능이 좋음

# MAC

![image](https://user-images.githubusercontent.com/37402136/205407988-6faa7491-05b3-402f-96be-9e81b4b2ddc0.png)

- Media Access Control
- 통신을 위해서 서로를 구분할 일종의 주소가 필요함
- IP 주소를 가지고 다시 MAC 으로 바꾸는 절차가 필요함 (ARP 를 사용)
- 같은 네트워크에 있다면 브로드케스트를 받을 수 있음. 하지만 다른 네트워크라면 도착지의 맥 어드레스를 안 다음에 통신을 시작할 수 있음

# 유니캐스트, 브로드캐스트, 멀티캐스트

### 유니캐스트

- 우리가 가장 많이 사용하는 트래픽
- 항상 출발지와 목적지의 주소를 알고 있어야 함
- 이더넷을 사용(로컬 이더넷에 붙어있는 모든 PC들에게 정보를 뿌리는 Shared 방식이라서 네트워크 통신 시 다 뿌려줌
- 자신의 랜카드 맥 어드레스와 목적지 맥 어드레스가 서로 다른 경우는 바로 그 프레임을 버림
- 같다면 CPU로 프레임을 올려보내면서 작업을 할 수 있게 함

### 브로드캐스트

- 로컬 랜에 붙어있는 모든 네트워크 장비들에게 보내는 통신
- FFFF.FFFF.FFFF 로 보내주면 랜카드는 비록 자신의 맥 어드레스와 같지는 않지만 브로드캐스트 패킷을 모든 장비가 CPU에 보내줌
- 이렇게 되면 트래픽이 매우 증가함.
- 상대편 맥 어드레스를 찾기 위한 ARP 동작을 위해서 브로드캐스트를 사용

### 멀티캐스트

- 200명 중에 150명만 보내고 싶을 때 사용
- 멀티캐스트는 보내고자 하는 그룹 멤버들에게만 한 번에 보낼 수 있기 떄문에 유니캐스트처럼 여러 번 보낼 필요도 없고, 브로드캐스트 처럼 받기 싫어하는 사람에게 까지 보낼 필요도 없음.
- 스위치나 라우터가 이 멀티캐스트 기능을 꼭 지원해야한다는 제약이 있음

# OSI 7 Layer

- Open System Interconnection
- 복잡한 네트워크 → dvide and conquer
- 층 별 표준화 → 호환성 확보, 비용절감
- 데이터의 흐름 파악 용이, 학습 도구로 활용
- 문제진단 해결 용이
- 통신 편리

![image](https://user-images.githubusercontent.com/37402136/205408103-6b780756-4b69-462a-ab4d-ba8f613e0959.png)

- L4 - L7 : User space
- L2 - L3 : Kernel space
- L1 : Physical space

# Protocol

- 규약
- 네트워크에서의 P 는 대부분이 Protocol임
