### ISSUE TITLE
4. 네트워크 장비에 관한 이야기 

### ISSUE THREAD

**Issue by hhhyunwoo** [WhiteKow/hoony-easy-written-cisco-networking-study#2]

**Comment by hhhyunwoo** [comment]
# 4. 네트워크 장비에 관한 이야기

## 랜카드

![image](https://user-images.githubusercontent.com/37402136/206455292-580a91d1-0a1a-40ef-9be5-7e49d77e1e34.png)

- 유저의 데이터를 케이블에 실어서 허브나 스위치, 혹은 라우터 등으로 전달해주고 자신에게 온 데이터를 CPU에게 전달해주는 역할
- 즉, 랜에 접속하기 위한 카드처럼 생긴 것!
- 선택 시 생각해야하는 것
    - 종류 (네트워킹 방식에 따라 나뉨)
        - 이더넷용 랜카드
        - 토큰링용 랜카드
        - FDDI
        - ATM용
    - PC의 버스 방식 (컴퓨터에서 데이터가 날아다니는 길의 방식을 의미함)
        - PCI
        - ISA
        - EISA
- 몇년전까지만 해도 10Mbps 용 랜카드가 일반적이었음. 즉 1초에 1MB
    - 하지만 OSI 7 Layer를 봐서 알겠지만 여러 헤더가 붙고 오버헤드가 발생함
- IRQ (Interrupt Request)
    - 목적지가 자신의 랜카드 맥어드레스와 일치하는 데이터가 들어왔을 때 랜카드는 컴퓨터의 CPU에 인터럽트를 걸고 요청을 함

## Hub

- Multiport Repeater
    - 허브는 포트가 여러 개 달린 장비인데, 한 포트로 들어온 데이터를 나머지 모든 포트로 뿌려줌!
    - 리피터는 데이터 전송 시 전달을 해주는 역할을 함
        - UTP 케이블 최대 전송 거리를 넘기기 위해 ~ 등
- 랜카드가 설치된 각각의 PC들은 케이블을 타고 바로 이 허브에 연결됨. 허브에 연결된 PC끼리는 서로 통신이 가능함.
- 허브끼리 연결을 하게 되면 마치 1대의 허브처럼 동작이 가능함.
- 종류
    - 이더넷용
    - 토큰링용
    - 일반 허브
    - 패스트 허브
- 허브의 동작 방법
    - 1번 PC가 데이터 전송 → 1번 포트를 제외하고 나머지 모든 포트로 데이터 전송 → 각 PC의 랜카드가 자신에게 온 것인지 확인하고 자기 맥어드레스가 아니면 버림
- 이더넷 허브는 CSMA/CD 의 적용을 받음. → 콜리전 도메인에 있다는 의미. 즉, 하나의 PC가 허브에 데이터를 보내고 있을 때 또 다른 PC가 데이터를 보내려고 하면 콜리전 발생
- 허브를 계속 연결해 나갈 수록 콜리전 도메인의 크기는 점 점 커짐

## 허브의 한계

- Shared Hub
    - 허브에 연결된 모든 PC들은 하나의 콜리전 도메인에 있기 때문에, 어느 한 순간에는 한 PC만 데이터를 보낼 수 있음

## 허브의 종류

- 인텔리전트 허브
    - Network Management System 에서 모든 데이터를 분석하고 제어도 할 수 있음
    - CSMA/CD 특징 떄문에 문제가 생긴 PC가 계속 이상한 데이터를 보내고 있다면 그것을 탐지해서 isolation 시킬 수 있음. → Auto Partition 기능
- 더미 허브
- 세미인텔리전트 허브
    - 더미 허브인데 인텔리전트 허브와 연결하면 인텔리전트가 됨

## 브리지와 스위치

- 아무리 빠른 속도의 허브를 쓰더라도 어느  한 순간에는 하나의 PC만 데이터를 보낼 수 있음.
- 이러한 문제를 해결하기 위해 콜리전 도메인을 나누어줄 수 있는 장비가 브리지와 스위치이다.
- 스위치가 나오기 전까지는 브리지가 해당 역할을 했지만 이제는 브리지보다 스위치가 더 빠르고 더 트렌드임

### 허브 vs 스위치

- 허브가 더 쌈
- 허브가 스위치보다 더 빠름
    - 들어온 데이터에게 해주는 일이 따로 없기 때문에
- → 어떠한 데이터가 돌아다니느냐 하는 것을 알고 판단해야함

### 브리지의 역할

- 허브로 만들어진 콜리전 도메인 사이를 반으로 나누고 중간에 다리를 놓는 것
    - 중간에 서서 브리지 테이블을 보면서 통신이 다리 한쪽에서만 일어나면 다리를 못건너가게 하고, 통신이 다리를 통과해야 가능하면 그때만 다리를 건너게 해준다!

### 브리지/스위치의 기능

- Learning
    - 들어온 데이터가 브리지 테이블(맥 어드레스 테이블)에 없으면 기록한다
- Flooding
    - 들어온 포트를 제외한 나머지 모든 포트로 뿌린다.
    - 들어온 프레임이 찾아가는 주소가 만약 브리지가 가지고 있는 브리지 테이블에 없는 주소라면 flooding 을 함
    - 브로트캐스트나 멀티캐스트의 경우에도 발생함
- Forwarding
    - 해당 포트로 건네준다.
    - 목적지의 맥 어드레스를 자신의 브리지 테이블에 가지고 있고, 이 목적지가 출발지의 맥 어드레스와 다른 세그먼트에 존재하는 경우에 일어남 .
- Filtering
    - 브리지를 못 넘어가게 막음
    - 출발지와 목적지가 같으 ㄴ세그먼트에 있는 경우
    - 이러한 기능 때문에 허브와는 다르게 콜리전 도메인을 나누어 줄 수 있는 것
- Aging
    - Time To Live
    - 계속 저장할 수 없으니, 일정 시간이 지나면 해당 정보 삭제
    - 다시 들어오면 refresh 진행

### 브리지 vs 스위치

- 이름이 다름
- 스위치가 더 비쌈
- 스위치가 더 잘나감

## Looping

- 프레임이 네트워크 상에서 무한정으로 뱅뱅 돌기 때문에 이더넷의 특성상 네트워크가 조용해야 데이터 전송을 할 수가 있는데, 다른 녀석들이 계속 네트워크가 조용해지기를 기다리기만 할 뿐 데이터 전송을 불가능해지는 상태를 의미함
- 루핑이 발생하면 통신도 안되고 문제도 찾기 어려움
- 스위치 끼리 다리가 두개가 놓여있으면 장비 간 통신의 길이 두가지가 되기 때문에 루핑이 발생함

### 스패닝 트리 알고리즘

- 브리지나 스위치에 목적자까지의 경로가 두 개 이상 존재하면 반드시 루핑이 발생하고, 이를 막는 것이 스패닝 트리 알고리즘임
- 스패닝 트리는 자동으로 루핑을 검색해서 이런 루핑이 발생할 수 있는 상황을 미리 막아줌.
- 또한 하나를 제외하고 나머지 경로를 자동으로 막아두었다가 기존 경로에 문제가 생기면 막아놓은 경로를 풀어서 데이터를 전송함 (Fault Toleration)

## 라우팅 vs 스위칭

- 비교
    - 라우터가 스위치보다 비쌈
    - 스위치가 더 빠름
    - 스위치가 구성이 더 쉬움
- 하지만 브로트 케스트 도메인 분리를 위해서 라우터 없이는 문제를 해결할 수가 없다.
- 전 세계에서 하나의 브로트 케스트 도메인을 사용한다면?
    - 하루에도 수 많은 PC들이 ARP 를 사용하는데, 이때마다 계속 브로드케스팅이 발생함
    - CPU 성능도 낮춤
- 따라서 브로드케스트 도메인을 나누는 것은 매우 중요함
- 스위치 만으로는 브로드 케스트 도메인을 나눌 수가 없음. 라우터가 필요!
- → 스위치냐 라우터냐의 답은! 적당히 사용해야함

**Comment by ChanhuiSeok** [comment]
### 랜카드 (네트워크 어댑터 혹은 Network Interface Card)
- 유저의 데이터를 케이블에 실어 허브나 스위치, 라우터 등으로 전달해주고 자신에게 온 데이터를 CPU에게 전달해주는 역할을 함
- 대부분 이더넷용 랜카드 사용
- 내가 목적지인 데이터가 들어왔을때 랜카드는 컴퓨터의 CPU에 자기가 가지고 있던 IRQ를 이용해서 인터럽트를 건다.
- 랜카드가 있어서 인터넷을 쓸 수 있는 것이다.

### 허브
#### 개요
- 멀티포트 리피터라고 말할 수 있다. 한 포트로 들어온 데이터를 나머지 모든 포트로 뿌려준다. 허브에 연결된 모든 PC들은 서로 간에 통신이 가능하다.
    - 리피터 : 중간에서 들어온 데이터를 다른 쪽으로 전달해 주는 역할.

#### 콜리전 도메인 및 한계
- ‘허브에 붙어 있는 모든 것들은 같은 **콜리전 도메인**에 있다’라고 말함.
    - 허브에 붙어있는 PC가 통신 시 다른 모든 PC는 통신을 할 수 없고, 콜리전 발생 시 모든 PC가 영향을 받는 개념
- 허브는 10Mbps 허브에 20대 PC를 연결하면, 실제는 20으로 나눈 만큼의 속도를 각자 쓰는 셈이 된다. 그리고 한 번의 콜리전 발생 시, 그 허브에 붙어있는 모든 PC가 영향을 받는다.

#### 종류
- 인텔리전트 허브, 더미 허브, 세미인텔리전트 허브 등이 있음
- 인텔리전트 허브 : 지능형 허브. NMS(네트워크 관리 시스템)에서 모든 데이터 분석 및 제어 가능
    - 대형 네트워크 등에서는 필요하더라도 사무실, PC방 등에선 별로 필요가 없음
    - 이더넷의 CSMA/CD 특징 때문에, PC가 이상한 데이터를 허브로 계속 보내면 다른 모든 PC도 통신 불능에 빠진다. 인텔리전트 허브는 문제 PC의 포트를 찾아 자동으로 고립시키는 역할도 해 준다.
    - Auto Partition : 위처럼 분리(고립)된 포트는 허브에서 램프로 표시되어 바로 어떤 PC인지 알게 되는데 그 기능을 말함.
- Stackable vs Standalone → 스택처럼 쌓아서 연결 가능 vs 단독으로 사용할 때 씀
    - 스태커블 장비는 단독형을 쌓아서 연결하는 것보다, 서로 간의 연결이 훨씬 효율적으로 설계됨
    - 혼자 있는 것보다 여러 대가 스택으로 연결되면 훨씬 더 좋은 성능 발휘

### 스위치
- 허브는 콜리전 도메인이 너무 커지는 상황을 조심해야 함(통신 속도가 점점 떨어지므로)
    - 이러한 문제 해결을 위해 브리지 또는 스위치가 나왔다. 브리지는 원조이고, 더 빠른 스위치가 나왔다.
- 스위치는 1-2번 PC 사이에 통신이 일어나도, 다른 PC들도 동시에 통신 가능하므로 허브와 큰 차이가 있다.
- 스위치는 각각 포트에 연결된 PC가 독자적으로 10, 100Mbps 속도를 가진다. (허브는 나눠가진다고 했다.)
- 지금은 스위치 가격이 많이 내려서 허브 대신 스위치를 주로 쓴다.

### 브리지
스위치를 이해하려면 브리지를 먼저 알고 넘어가야 함. (스위치의 원조격)
- 네트워크 규모가 커지고 통신량 증가 시 **콜리전 도메인을 나누어 주기 위해서 사용**
- **허브로 만들어진 콜리전 도메인을 반으로 나누고, 중간에 다리를 놓는 격**
    - 그러면 그 나누어진 것들끼리 동시에 통신이 가능하다.

#### 브리지가 하는 일
- Learning : 출발지의 맥 어드레스를 저장해 놓는다.
    - PC A가 통신을 위해 프레임 내보내면, 그 때 이 PC의 맥 어드레스를 읽어 맥 어드레스 테이블 혹은 브리지 테이블에 저장해 놓는다.
    - 나중에 어떤 PC가 A에게 통신할 경우, 브리지 테이블을 참고하여 다리를 건너게 할 지 말지를 결정한다.
- Flooding : 브리지 테이블에 없는 주소라면? 들어온 포트를 제외한 다른 모든 포트로 프레임을 뿌린다. 브로드캐스트의 경우도 목적지가 모든 PC이므로 Flooding이 발생한다.
- Forwarding : 목적지가 어딘지 알고 있는데 그 **목적지가 다리를 건너가야만 하는 경우, 포워딩이 발생**한다. (Flooding과 달리, 오직 그 해당 포트 쪽으로만 프레임을 뿌려준다.)
- Filtering : 브리지를 못 넘어가게 막는다. 브리지 테이블에 목적지 맥 어드레스가 있고, 출발지와 목적지가 같은 세그먼트에 있으면 브리지를 건너지 않아도 되기 때문이다. 이 **필터링**을 통해, **허브와는 다르게 콜리전 도메인을 나누어 줄 수 있게 된다.**
- Aging : 브리지 테이블에 저장된 주소는 일정 시간(디폴트 5분)동안 그 출발지 주소를 가진 프레임이 들어오지 않으면 삭제시킨다.
    - 리플래시 : 에이징 타이머를 리플래시한다고 부른다. 5분이 끝나기 전, 그 주소가 브리지로 또 들어오면 타이머를 리셋하고 처음부터 다시 카운트하는 것을 말한다.

#### 브리지와 스위치
- 데이터 링크 레이어 계층에 있고 하는 일이 비슷하다.
- 차이점 : 이름이 다르고, 가격이 다르고, 인기도가 다르다.
    - 그 외에도… 스위치는 브리지에 비해 제공하는 포트 수가 훨씬 많고, 서로 다른 속도를 연결해 주는 기능도 제공하는 등 차이점이 있다.

### Looping
- 브리지나 스위치에서 자주 발생하는 현상이다.
- 프레임이 네트워크상에서 무한정 뱅뱅 돌아서, 이더넷 특성상 네트워크가 조용해야 데이터 전송 가능한 다른 녀석들이 계속 조용해지기를 기다리기만 할 뿐 전송이 불가능한 상태
    - 브리지나 스위치 디자인에서 주의해야 할 사항임
- 자동으로 루핑을 막아주는 스패닝 트리 알고리즘으로 해결할 수 있다.

### 스패닝 트리 알고리즘
- 스위치나 브리지에서 발생할 수 있는 **루핑을 미리 막고자**, 두 개 이상의 경로가 발생하면 하나를 제외하고 나머지 경로를 자동으로 막아두었다가, 기존 경로에 문제가 생기면 막아놓은 경로를 풀어서 데이터를 전송하는 알고리즘

### 라우팅 vs 스위칭
- 라우터가 필요한 이유
    1. 브로드캐스트 : 브로드캐스트 영역을 나누는 것이 중요한데 이것을 라우터가 해 준다. (참고 - 스위치가 라우터 역할까지 하는 경우 `레이어 3 스위치`라고 부름) 스위치로 계속 구매해서 다 구성하면 콜리전 도메인은 커지지 않겠지만 브로드캐스트 도메인이 늘어나게 된다. 그것을 라우터가 나눠 준다. 
    2. 로드 분배 : 여러 개 경로를 가지고 있으므로 데이터가 여러 경로를 타고 날아갈 수 있음. 그러므로 한쪽 경로에 문제가 생겨도, 바로 다른 경로를 타고 날아갈 수 있다.
    3. 그 외에 프로토콜이나 데이터 크기, 중요도 등 여러 상황에 따라 트래픽 전송 순서를 조정해 주는 QoS(Quality of Service) 기능도 제공함
- 결론 : 라우터와 스위치를 적당히 사용한다.

**Comment by jjangsungwon** [comment]
## PART 04. 네트워크 장비에 관한 이야기

### 랜카드
- `랜에 접속하기 위한 카드처럼 생긴 것`
- 유저의 데이터를 케이블에 실어서 허브나 스위치, 혹은 라우터 등으로 전달해주고 자신에게 온 데이터를 CPU에게 전달
  - 내가 목적지인 데이터(목적지 주소가 자신의 맥 어드레스와 일치하는 데이터)가 들어왔을 때 랜카드는 컴퓨터의 CPU에 자기가 가지고 있던 IRQ(인터럽트 요청)를 이용해서 인터럽트를 검
- 환경에 따라 이더넷용, 토큰링용, FDDI, ATM 등으로 구분 (대부분 이더넷)
- 설치 장소에 따라 데스크톱용, 노트북용 등으로 구분
  - 모양은 다르지만 하는 일은 똑같다. 하지만 자신이 가지고 있는 PC 에 맞는 것을 구매해야함 
- 버스 방식
  - 버스: 컴퓨터에서 데이터가 날아다니는 길
  - PCI, ISA, EISA 존재 (최근은 PCI 를 주로 사용)
- 속도에 따른 구분
- 랜카드에 접속하는 케이블 종류에 따른 구분 (TP, BNC, AUI)

### 허브
- 멀티포트 리피터 (Multiport Repeater)
  - 멀티포트: 포트가 여러개 붙어있음
  - 리피터: 재전송
    - 케이블이 갈 수 있는 최대 거리 이상 떨어진 장비 간의 연결에 용이 
  - 종합: 한 포트로 들어온 데이터를 나머지 모든 포트로 뿌려줌
- 랜카드가 설치된 각각의 PC들은 케이블을 타고 허브에 연결됨
- 허브에 연결된 PC끼리는 서로 통신이 가능
- 허브는 서로 연결하면 마치 1대의 허브처럼 동작
- 랜카드에 맞는 허브를 선택 (속도 관련)
- 이더넷 허브는 CSMA / CD 의 적용을 받음 -> 하나의 PC가 허브에 데이터를 보내고 있을 때 또 다른 PC가 데이터를 보내려고 하면 콜리전이 발생 -> 같은 허브에 연결되어 있는 모든 PC들은 모두 같은 콜리전 도메인에 있다(`Shard Hub`) -> 허브에 붙어있는 하나의 PC에서 콜리전이 발생하면 모든 PC가 영향을 받음
  - 허브를 추가할수록 위 문제는 더 심각해짐. 콜리전 도메인 영역이 커지기 때문에 
- 셋팅이 간단함 (전원에 연결해서 스위치를 ON하고 케이블을 꽂아서 사용하면 됨)
- 종류
  - 인텔리전트 허브: NMS에서 모든 데이터 분석 및 제어 가능 (ex, Auto Partition)
  - 더미 허브: 기본적인 허브
  - 세미인텔리전트 허브: 혼자 있을 때는 더미 허브, 인텔리전트 허브랑 같이 있으면 인텔리전트 허브

### 스위치
- 허브의 콜리전 도데인 문제를 해결할 수 있는 장비
- 허브는 일차선 도로, 스위치는 포트 수별로 차선이 만들어진다고 생각하면 이해가 쉬움
- 허브 vs 스위치
  - 허브 장점
    - 허브는 스위치보다 저렴함 (요즘은 스위치도 가격기 많이 내려감)
    - 데이터 처리 속도가 일반적으로 빠름 (들어온 데이터에 해줄 일이 별로 없어서)
  - 스위치 장점
    - 데이터 처리 방법 우수 (컬리전 도메인 해결)
    - 데이터 전송 에러 복구 등 여러 가지 기능
  - 네트워크 트래픽이 적으면 허브로도 충분할 수도 있음. 무조건 스위치는 틀린 생각
  - 스위치가 아무리 콜리전 도메인을 나누었다 하더라도 서버와의 통신은 어느 한순간에는 하나의 PC만 가능함 (서버가 한 대인 경우)

### 브리지
- 브리지는 말 그대로 다리를 의미함
- 허브로 만들어진 콜리진 도메인 사이를 반으로 나누고 중간에 다리를 놓음
- 브리지 테이블을 통해서 다리를 건널 수 있는지 판단

### 브리지/스위치 기능
- Learning
  - 통신을 위해서 프레임을 내보내면 해당 PC의 맥 어드레스를 읽어서 맥 어드레스 테이블(브리지 테이블)에 저장
  - 브리지 테이블을 활용해서 다리를 건너게 할 것인지 결정
- Flooding
  - 들어온 포트를 제외한 나머지 모든 포트로 뿌림
  - 브리지 테이블에 없는 주소가 들어올 때 사용
  - 브로드캐스트, 멀티캐스트의 경우에도 말생
- Forwarding
  - 목적지의 맥 어드레스를 자신의 브리지 테이블에 가지고 있고, 목적지가 출발지의 맥 어드레스와 다른 세그먼트에 존재하는 경우에 발생
  - 목적지가 어디 있는지를 알고 있는데 그 목적지가 다리를 건너가야만 하는 경우에 발생
  - Flooding과 달리 모든 포트가 아닌 해당 포트쪽으로만 프레임을 뿌려줌
- Filtering
  - 브리지를 못 넘어가게 막는 것
  - 출발지와 목적지가 같은 세그먼트에 있는 경우
- Aging
  - 맥 어드레스를 평생 저장한다는 금방 브리지 테이블이 차버림
  - 특정 시간이 지나면 해당 주소 삭제
  - 다시 들어오면 리플래시 동작

### 브리지 vs 스위치
- 스위치가 빠름
  - 스위치는 처리 방식이 하드웨어로 구성 (처리 절차를 미리 칩에 구움). 브리지는 소프트웨어적으로 구성
  - 스위치는 포트별로 서로 다른 속도를 연결할 수 있음
  - 스위치는 브리지에 비해 제공하는 포트 수가 훨씬 많음
  - 스위치는 Cut-through 또는 Store-and-forward 방식 사용. 브리지는 Store-and-forward 방식 사용
    - Cut-through: 특정 비트(48)만 보고 동작. 에러 복구 능력이 떨어질 수 있음
      - Fragment-free  : 512비트 보고 동작. Cut-through 에 비해 에러 복구 능력 좋음

### Looping
- 프레임이 네트워크상에서 무한정으로 뱅뱅 도는 경우
- CSMA / CD 특성상 네트워크가 무용지물 상태로 빠지게 됨
- 스패닝 트리 알고리즘
  - 브리지나 스위치에 목적지까지의 경로가 두 개 이상 존재할 때 이를 막는 역할을 수행함
  - 두 개 이상의 경로가 발생하면 하나를 제외하고 나머지 경로를 자동으로 막아두었다가 기존 경로에 문제가 생기면 막아놓은 경로를 풀어서 데이터를 전송함

### 라우팅 vs 스위칭
- 브로드캐스트 영역(도메인)을 나눠주기 위해서는 라우터가 꼭 필요함 (레이어 3 스위치는 라우터 역할도 수행함)
- 라우터는 로드 분배 기능을 제공함. 여러 개의 경로를 가지고 있을 때 한쪽 경로에 문제가 생겨도 바로 다른 경로를 타고 날아갈 수 있음. 스위치도 로드 분배가 가능하지만 굉장히 제한적임
- 스위치와 라우터는 적당히 사용해야 함~~~~

### 허브, 스위치, 브리지, 라우터
- 허브: 한 포트로 들어온 데이터를 나머지 모든 포트로 뿌려줌
- 브리지/스위치: 콜리진 도메인 영역 분리
- 라우터: 브로드캐스트 영역 분리
