### ISSUE TITLE
5. IP 주소로의 여행

### ISSUE THREAD

**Issue by hhhyunwoo** [WhiteKow/hoony-easy-written-cisco-networking-study#3]

**Comment by hhhyunwoo** [comment]
# 5. IP 주소로의 여행

## IP 주소

- 원래는 이진수 `32자리`로 되어 있음. 각 8자리 (십진수로 하면 최대 `255`) 즉, 옥텟 사이에는 점을 찍음
- 인터넷에서 사용되는 프로토콜이 바로 `TCP/IP` 이고, TCP/IP 가 사용하는 주소가 바로` IP 주소`이므로 제대로 이해할 필요가 있음

## 라우터에서의 IP 주소

- 보통 쓰는 라우터에 배정해야 하는 IP 주소는 `두 개`이다. 하나는 `이더넷 인터페이스` 용. 다른 하나는 `시리얼 인터페이스` 용
- 이더넷용은 우리가 부여받은 번호 중에 하나를 쓰는 것
- 시리얼은 우리가 접속하는 ISP 업체에 따라 다르기 때문에 문의해서 써야함

## IP 주소의 구성 (네트워크와 호스트)

- 네트워크는 하나의 브로드캐스트 영역
    - 하나의 PC가 데이터를 뿌렸을 때 그 데이터를 라우터를 거치지 않고 바로 받아볼 수 있는 영역
- 호스트는 각각의 PC 또는 장비라고 생각할 수 있음
    - 모든 PC가 서로 달라야함

### IP 주소의 클래스

- A부터 B, C, D, E 로 구분됨.
- **2개는 빠짐**
    - 하나는 0 으로 가득찬 가작 작은 수 ⇒ `네트워크 자체의 주소`
    - 다른 하나는 제일 큰 수 ⇒ 해당 네트워크의 `브로드 캐스팅`을 위한 것

![image](https://user-images.githubusercontent.com/37402136/208136479-0f6b4deb-9400-49d0-a7c1-ad3fefec1544.png)

- A 클래스
    - 맨 앞이 0으로 시작
    - 하나의 네트워크가 가질 수 있는 호스트 수가 가장 많은 클래스
    - 네트워크 번호가 1-126으로 시작
    - 한 네트워크 안에 들어갈 수 있는 호스트 수 : 16,777,214
- B 클래스
    - 맨 앞이 10 으로 시작
    - 네트워크 번호가 128.1 - 191.255 로 시작
    - 호스트 수 : 65.534
- C 클래스
    - 맨 앞이 110 으로 시작
    - 네트워크 번호가 192.0.0 - 223.255.255 로 시작
    - 호스트 수 : 254
- D 와 E 클래스는 멀티캐스트용과 연구용으로 사용 됨

## 서브넷 마스트

- 서브넷 마스크는 IP 주소에 있어서 매우 중요
- 예를 들어 클래스 B 주소를 받았을 경우 하나의 네트워크가 65000여 개의 호스트를 가지기 때문에 바로 구성하게되면 브로드캐스트의 영향이 너무 큼. 따라서 구분을 하기 위해서 서브넷마스크를 사용함
- **서브넷 마스크는 주어진 IP 주소를 네트워크 환경에 맞게 나누어 주기 위해서 씌워주는 이진수의 조합**
    - → 브로드 캐스트 영역을 나누는 것과 IP 주소를 아끼기 위한 것
- **각각의 서브넷 간의 통신은 라우터를 통해서만 가능함!**
    - 서브넷 마스크를 가지고 나누어서 만들어낸 서브넷도 엄연히 하나의 네트워크니까 서로 간의 통신은 라우터를 통해서만 가능함.
- 서브넷 마스크를 만들 때는 이진수로 봤을 때 여러개의 1사이에 0이 오면 안됨

### 디폴트 서브넷 마스크

![image](https://user-images.githubusercontent.com/37402136/208136510-c741435a-90ca-4e63-ae8e-ebe23b904d69.png)

- 서브넷 마스크는 IP 주소를 가지고 어디까지가 네트워크 부분이고, 또 어디까지가 호스트 부분인지를 나타내는 역할을 함
- 1인 부분은 네트워크, 0인 부분은 호스트
- 기존 IP와 AND 연산을 함
- 주어진 네트워크를 하나도 나누지 않고 그대로 다 쓰는 경우는 디폴트 서브넷 마스크를 사용함. 하지만 주어진 네트워크를 나누어서 쓰는 경우는 디폴트 서브넷 마스크를 수정해서 사용함
- 하나의 주소를 서브넷 마스크를 씌워서 작은 네트워크로 만드는 것을 서브네팅이라고 함

## 서브넷 만들어보기 예시

Q) 공인 IP 주소를 210.100.1.0(서브넷 마스크 255.255.255.0) 네트워크를 받았습니다. 그런데 네트워크 관리자인 여러분은 이 공인 주소를 이용해서 PC가 30대인 네트워크를 최소 4개 이상 만든 후 이들 네트워크를 라우터를 이용해서 서로 통신하게 하려고 합ㄴ디ㅏ. 이 경우 여러분이 서브넷 마스크를 만든다면 어떻게 해야할 까요?

⇒ 

- 해당 네트워크는 C 클래스 네트워크임.
- 이 주소로 네트워크를 최소 4개 이상 만들려면 주어진 디폴트 서브넷 마스크 변경이 필요함
- 호스트가 30개가 되기 위해서는 이진수가 5자리가 필요함
    - 호스트 부분이 모두 0 이거나 모두 1인 경우는 못쓰니깐 2를 빼줘야함
    - 2^(호스트 비트 수) - 2
- 즉, 210.100.1.ssshhhhh 가 되어야 함
    - → 255.255.255.1110 0000(224) 의 서브넷 마스크를 사용해야함

![image](https://user-images.githubusercontent.com/37402136/208136552-47578caa-73bd-451c-942b-bed05e3cb4d4.png)

Q) 받은 공인 주소는 201.222.5.0(255.255.255.0) 이고 고객이 원하는 것은 이 주소를 잘라서 20개 이상의 작은 네트워크를 만드는데, 한 네트워크가 최소한 5개의 호스트를 가져야 한다. 

⇒

- 호스트가 5개가 되기 위해서는 최소 3비트가 필요함
- 255.255.255.1111 1000
- 
![image](https://user-images.githubusercontent.com/37402136/208136610-c2a2058b-d013-43d9-967b-77fe696a883e.png)

**Comment by ChanhuiSeok** [comment]
### IP 주소
- TCP/IP 프로토콜을 만들 때 이 프로토콜을 사용하는 모든 장비들을 구분해주기 위해 만든 주소. 서로 간의 통신을 위해서 이들을 구분할 주소가 필요했다.
- IP 주소는 원래 이진수 32자리이고 사용자에게는 익숙한 십진수 방식으로 고쳐서 사용하고 있다.

### 라우터에서 IP 주소 이해하기
- 라우터에 배정해야 하는 IP 주소는 두 개
    - 이더넷 인터페이스용 : 우리가 부여받은 주소 중에 하나
    - 시리얼 인터페이스용 : 우리가 접속하는 ISP 업체에 따라 다르므로 인터넷 제공업체에 문의

### 네트워크 부분과 호스트 부분
- 네트워크 부분 : 한 네트워크는 하나의 브로드캐스트 영역이라는 의미. 즉, 라우터를 거치지 않고 통신이 가능한 영역이다. 라우터가 브로드캐스트 영역을 나누는 역할이기 때문
- 호스트 부분 : 각각의 PC나 장비를 말한다.
- IP 주소 자체는 네트워크 부분과 호스트 부분으로 나누어져 있다. 그러므로, 어떤 네트워크라도 **하나의 네트워크 안에서는** 네트워크 부분은 모두 같아야 하고, 호스트 부분은 모두 달라야 정상적인 통신이 일어난다.
- 예: 203.240.100.1~203.240.100.255 까지면 네트워크 부분은 203.240.100 이다.
- IP 주소 중에, 네트워크 부분만이 라우터가 라우팅을 할 때 참고하는 부분이 된다.
- 라우터는 다른 네트워크로 갈 때만 필요하지, 같은 네트워크 안에서의 통신에서는 필요가 없다.

### IP 주소의 클래스
- 클래스는 A~E 까지로 구분된다. 클래스에 따라 어디까지가 네트워크 부분인지, 호스트 부분인지 나뉜다.
    - 네트워크의 크기에 따른 구분을 함
- 클래스 A : IP 주소가 1에서 126으로 시작하는 네트워크. 하나의 네트워크가 가질 수 있는 호스트 수가 가장 많은 클래스이다. 즉, 네트워크 부분은 맨 앞의 십진수 부분, 나머지 24비트(나머지 세 개 십진수)가 호스트 부분이다.
- 클래스 B : 맨 앞이 반드시 10(이진수)으로 시작됨. 따라서 128.0.0.0~191.255.255.255 범위이다. 맨 앞 두자리 십진 수부분이 네트워크 부분, 나머지 두 자리가 호스트 부분을 나타낸다.
- 클래스 C : 맨 앞이 110(이진수)으로 시작된다. 그러므로 IP 주소가 192에서 223으로 시작하는 네트워크이다. 네트워크 부분은 앞의 세자리 십진수 부분, 호스트 부분은 마지막 한 자리 부분이다.
    - 가질 수 있는 호스트 수는 254개 (0은 네트워크 번호, .255는 브로드캐스트용)
- 그 외에 클래스 D, E도 있다. D는 멀티캐스트용, E는 연구용이다.

### IP 주소의 활용
- IP 주소를 배정할 때는, 그 네트워크에 몇 개의 호스트가 접속 가능한지 먼저 확인하고 배정하는 주소가 이 호스트를 모두 포함할 수 있는지를 확인해야 한다. (예: 300개 호스트가 있는 네트워크에 클래스 C 하나를 배정하면 부족하다.)

### 서브넷 마스크
- 보통 어떤 IP 주소를 배정받으면 이 주소를 그대로 사용하지 않는다. 만약 클래스 B 주소를 받았는데, 그냥 사용하면 하나의 네트워크가 65000여개의 호스트를 가지며 너무 커서 브로드캐스트의 영향도 크고, 아무것도 할 수 없게 된다.
- 즉, **나누어 써야 할 때 서브넷 마스크를 씌워서 네트워크를 나눠준다.**
- 모든 IP 주소에는 서브넷 마스크가 따라다닌다. 서브넷 마스크는 **IP 주소에서 어디까지 네트워크 부분인지, 어디까지 호스트 부분인지 나타내는 역할을 한다.**
    - 네트워크는 서브넷 마스크가 이진수로 1인 부분, 호스트는 서브넷 마스크가 이진수로 0인 부분이다.
    - 예: 210.100.100.1의 IP 주소와 255.255.255.0의 서브넷 마스크 → 210.100.100.0이 서브넷 네트워크
    - 이진수 AND 연산을 해서(IP 주소와 서브넷 마스크끼리 연산) 네트워크 주소를 파악하면 된다.
    - 하나의 주소를 서브넷 마스크를 씌워서 작은 네트워크로 만드는 것을 `서브네팅` 이라고 한다.

### 서브넷 마스크의 성질
- 서브넷 마스크로 만들어진 네트워크 즉 서로 나뉜 서브넷끼리는 라우터를 통해서만 통신이 가능하다.
    - 서브넷 마스크에 따라, 서로 다른 네트워크가 될 수 있기 때문이다.
- 이진수로 썼을 때 ‘1’ 이 연속적으로 나와야 한다. 중간에 0이 있어도 안 된다.

**Comment by jjangsungwon** [comment]
블로그 포스팅으로 대체합니다~ (https://jjangsungwon.tistory.com/151)
