### ISSUE TITLE
6. 스위치를 켜라!

### ISSUE THREAD

**Issue by hhhyunwoo** [WhiteKow/hoony-easy-written-cisco-networking-study#4]

**Comment by hhhyunwoo** [comment]
# 6. 스위치를 켜라!

## 스위치

- 허로 만들어진 콜리전 도메인 사이를 반으로 나누고 중간에 다리를 놓아서, CSMA/CD 문제를 해결함

## 스패닝 트리

- 스위치나 브리지에서 발생하는 Looping 을 막아주기 위한 프로토콜
    - 출발지부터 목적지까지의 경로가 2개 이상 존재할 때 1개의 경로만을 남겨두고 나머지는 모두 끊어두었다가, 사용하던 경로에 문제가 발생하면 그 때 끊어두었던 경로를 하나씩 살림

### Bridge ID

- 브리지의 ID
- Bridge Priority (16bit) + MAC Address (48bit)
- Bridge Priority
    - 0 ~ 65535
    - default : 중간 값 32768 == 8000

### Path Cost

- 브리자가 얼마나 가까이 그리고 빠른 링크로 연결되어 있는지를 알아내기 위한 값
- 기본적으로는 1,000Mbps 를 두 장비 사이의 링크 대역폭으로 나눈 값을 사용했음
- 소수 점이 나오면서 표준 값이 생김

### 스패닝 트리의 프로토콜

1. 네트워크 당 하나의 Root Bridge 를 가진다
    - 네트워크는 스위치나 브리지로 구성된 하나의 네트워크를 의미함. 따라서 라우터에 의해 나누어지는 브로드캐스트 도메인이 하나의 네트워크라고 볼 수 있음
    - Root Bridge 는 대장 브리지로 볼 수 있음. 스패닝 트리 프로토콜을 수행할 때 기준이 되는 브리지
2. Root Bridge 가 아닌 나머지 모든 브리지는 무조건 하나씩의 Root Port 를 가진다
    - Root Port 는 루트브리지에 가장 빨리갈 수 있는 포트를 말한다.
3. 세그먼트 당 하나씩의 Designated Port 를 가진다
    - 쉽게 말해 지정포트
    - 세그먼트는 브리지 또는 스위치 간에 서로 연결된 링크라고 볼 수 있음

![image](https://user-images.githubusercontent.com/37402136/209356716-c744fd3d-f51d-40a0-85a2-2df6a16e681e.png)

### STP 에서 Root Bridge 뽑기

- 무조건 낮은 BID를 갖는 브리지가 대장이 됨

### STP 에서 루트포트와 데지그네이티드 포트 정하기

1. 누가 더 작은 Root BID를 가졌는가?
2. Root Bridge 까지의 Path Cost 값은 누가 더 작은가?
3. 누구의 BID(Sender BID)가 더 낮은가?
4. 누구의 Port ID가 더 낮은가?
- `BPDU`
    - Bridge Protocol Data Unit
    - 루트 브리지의 BID인 Root BID, Root Path Cost, Sender BID 그리고 Port ID 등의 정보가 실려있음
    - 스패닝 트리 정보를 브리지끼리 주고 받기 위해서 사용하는 특수한 프레임
    - 브리지나 스위치가 부팅을 하면 이들은 각각의 포트로 BPDU를 매 2초마다 내보내면서 서로의 스패닝  트리 정보를 주고 받게 된다.

### STP의 5가지 상태 변화

- `Disabled`
    - 포트가 고장나서 사용할 수 없거나 네트워크 관리자가 포트를 일부러 닫아놓은 상태
    - 데이터 전송 X
    - MAC 배우기 X
    - BPDU 주고받기 X
- `Blocking`
    - 스위치를 맨 처음 켜거나, Disabled 되어 있는 포트를 살렸을 때
    - 데이터 전송은 되지 않고 오직 BPDU 만 주고받을 수 있음
    - 데이터 전송 X
    - MAC 배우기 X
    - BPDU 주고받기 O
- `Listening`
    - 블로킹 상태에 있던 스위치 포트가 루트 포트나 데지그네이티드 포트로 선정되면 포트는 바로 리스닝 상태로 넘어감
    - 데이터 전송 X
    - MAC 배우기 X
    - BPDU 주고받기 O
- `Learning`
    - 리스닝 상태에 있던 스위치 포트가 포워딩 딜레이 디폴트 시간인 15초 동안 그 상태를 유지하면, 리스닝 상태는 러닝 상태로 넘어감
    - 비로소 MAC 을 배워서 Table을 만듬
    - 데이터 전송 X
    - MAC 배우기 O
    - BPDU 주고받기 O
- `Forwarding`
    - 스위치 포트가 러닝 상태에서 다른 상태로 넘어가지 않고, 포워딩 딜레이 디폴트 시간인 15초 동안 유지하면 포워딩 상태로 넘어감
    - 즉, 블로킹에서 포워딩으로 가려면 30초가 소요됨
    - 데이터 전송 O
    - MAC 배우기 O
    - BPDU 주고받기 O

### 실습

![image](https://user-images.githubusercontent.com/37402136/209356740-6365610f-ab99-440f-b325-00aa6d44d293.png)

### 스패닝 트리에 변화가 생기면?

- `Hello Time`
    - 루트 브리지가 얼마 만에 한번 씩 헬로 BPDU를 보내는지에 대한 시간
    - 디폴트는 2초
- `Max Age`
    - 브리지들이 루트 브리지로부터 헬로 패킷을 받지 못하면 맥스 에이지 시간 동안 기다린 후 스패닝 트리 구조 변경을 시작함
    - 즉, 특정 시간이 지나면 루트 브리지가 죽었다고 생각하고 새로운 트리를 만드는 것임
    - 디폴트 20초
- `Forwarding Delay`
    - 브리지 포트가 블로킹 상태에서 포워딩 상태로 넘어갈 때까지 걸리는 시간

## VLAN

- 스위치는 단순히 콜리전 영역을 나눠주는 역할 뿐만 아니라 라우터 없이 브로드캐스트 도메인을 나눌 수 있는 VLAN 기능을 제공함
    - 즉, 한 대의 스위치를 마치 여러대의 분리된 스위치처럼 사용하고, 또 여러 개의 네트워크 정보를 하나의 포트를 통해 전송할 수 있음
    - 가상 랜을 이용하면 하나의 스위치에 연결된 장비들도 브로드캐스트 도메인이 서로 다를 수 있음

![image](https://user-images.githubusercontent.com/37402136/209356756-4ef98a26-832c-434d-afdc-9b1b351c7750.png)

- 한 스위치에 붙어 있는 2번 3번 VLAN 네트워크끼리 통신하려면 반드시 라우터를 거쳐서만 가능함. 아무리 같은 스위치에 붙어있다고 하더라도 네트워크가 다르기 때문에 통신이 불가능함

### 트렁킹

- 여러 개의 VLAN 들을 한 번에 전송하는 방식
- ISL 방식
    - CISCO에서 만듬
- IEEE 802.1Q 방식
    - 표준
    - Native VLAN이 존재
        - 이름표가 붙지 않은 VLAN

### VTP

- VLAN Trunking Protocol
- 스위치들 간에 VLAN 정보를 서로 주고받아 스위치들이 가지고 있는 VLAN 정보를 항상 일치시켜 주기 위한 프로토콜
- 시스코만의 프로토콜

### VLAN 에 대한 정보

1. VLAN에 대해 아무것도 세팅하지 않았을 때도 Default VLAN은 이미 세팅이 되어 있음. VLAN 1 이 디폴트 VLAN으로 최초에 모든 포트가 다 VLAN 1에 속해 있음 
2. 각 스위치 마다 만들 수 있는 VLAN의 개수는 모두 다름
3. 스위치의 IP 주소 세팅은 VLAN 1에 진행함

ref. 
https://medium.com/humanscape-tech/스위치-스패닝트리-d6c1966aca94
https://winyong.tistory.com/47
http://trac.gateworks.com/wiki/linux/vlan

**Comment by ChanhuiSeok** [comment]
## 6장. 스위치를 켜라

### 스패닝 트리 프로토콜
- 브리지 ID와 Path Cost 개념 이해 필요
    - 브리지 ID : 8바이트이며 2바이트는 Bridge Priority, 6바이트는 맥 어드레스로 이루어짐
    - Path Cost : 길을 가는데 드는 비용, 즉 브리지가 얼마나 가까이, 빠른 링크로 연결되어 있는지 알아내는 값으로 작을수록 속도가 빠름
    - IEEE는 각 속도별로 path cost 값을 정수값으로 정의하여 사용 중

### 3가지 기본 동작
    - 첫째: 네트워크당 하나의 루트 브리지를 갖는다.
        - 라우터에 의해 나누어지는 브로드캐스트 도메인이 하나의 네트워크라고 생각하면, 하나의 브로드캐스트 도메인에 하나씩의 루트 브리지가 있는 것임. 루트 브리지는, STP 수행 시 기준이 된다.
    - 둘째: 루트 브리지 외 나머지 모든 브리지는 무조건 하나씩의 루트 포트를 갖는다.
        - 루트 포트는, 루트 브리지에 가장 빨리 갈 수 있는 포트를 말한다.(가장 가까운 포트)
    - 셋째: 세그먼트 당 하나씩의 데지그네이티드 포트를 갖는다.
        - 세그먼트는 브리지나 스위치 간에 서로 연결된 링크를 말하며, 여기서 반드시한 포트는 데지그네이트 포트로 선출되어야 한다.
    - 이처럼 STP에서는 루트포트와 데지그네이티드 포트가 아닌 다른 모든 포트는 다 막아버린다. 어떤 포트를 살릴지 결정하는 것이다.

### STP에서 힘 겨루기
- 위 3가지 기본 동작을 할 때 어떻게 순서를 정하는가? (누가 루트 브리지, 누가 루트 포트나 데지그네이티드 포트인지?)
    - 1단계: 누가 더 작은 Root BID(브리지 ID)인가?
    - 2단계: 루트 브리지까지의 Path Cost가 누가 더 작은가?
    - 3단계: 누구의 BID가 더 낮은가?
    - 4단계: 누구의 포트 ID가 더 낮은가?
- 브리지(스위치)는 스패닝 트리 정보를 주고받기 위해 BPDU라는 프레임을 사용한다. 여기에 root bid, root path cost, sender BID, port ID 등이 포함된다.
- 이 BPDU를 매 2초마다 내보내면서 서로의 스패닝 트리 정보를 주고받으며, 위 1~4단계를 거치며 어떤 BPDU가 가장 좋은지 결정한다. 즉 BPDU는 우체부라고 보면 된다.

### 스위치에서 대장 브리지(Root Bridge) 뽑기
- 1단계로 누가 더 작은 브리지 ID를 가지는지 본다고 했다. 대장 브리지는 무조건 낮은 BID를 갖는 녀석이 대장이 된다. (브리지 ID는 Priority와 맥 어드레스로 구성. Priority가 낮으면 무조건 낮은 BID임)
- 스위치들은 부팅 후 BPDU를 보내며 브리지 ID를 비교해 가며 대장 브리지를 찾아 나간다.

### Non Root Bridge(졸병 브리지)의 루트 포트 선출하기
- 루트 브리지 선출 끝나고, 스위치들의 루트 포트 선출이 시작된다.
- 루트 포트는 `루트 브리지에 가장 가까이 있는 포트`이다. 즉, 각 스위치에서 Root Path Cost가 가장 적게 드는 포트가 가장 가까이 있다는 것이 된다.

### 데지그네이티드 포트 선출하기
- 데지그네이티드 포트를 뽑아야, 스패닝 트리에서 어떤 포트를 풀어주고 어떤 포트는 막을지 결정된다.
- 세그먼트 상에서 Root Path Cost를 서로 비교해 더 작은 cost를 가진 포트가 데지그네이티드 포트로 선출된다.
- 뽑히지 않은 나머지 포트는 Non Designated 포트로 지정한다.

### STP의 5가지 상태변화
- 스패닝 트리 구성 시 다음과 같은 5가지 상태를 거친다.
    - Disabled → Blocking → Listening → Learning → Forwarding
    - <img src="https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Ft1.daumcdn.net%2Fcfile%2Ftistory%2F99E901465A7043D238" width="400"> ([출처](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Ft1.daumcdn.net%2Fcfile%2Ftistory%2F99E901465A7043D238))
- 루트 포트와 데지그네이티드 포트는 포워딩 으로 만들어 데이터 전송이 가능하게 하고, Non Designated 포트는 블로킹 상태로 만든다.
블로킹은 BPDU 통신은 하되 데이터 전송이 불가능한 상태이다.

### 스패닝 트리에 변화가 생기던 날
- Non Root Bridged들이 지정된 시간 동안 패킷을 못 받으면, 중간 경로에 뭔가 문제가 발생했다고 생각한 뒤 스패닝 트리를 재편성한다.
    - 헬로 타임 : 루트 브리지가 얼마만에 한 번씩 헬로 BPDU를 보내는지에 대한 시간. (디폴트는 2초)
    - 맥스 에이지 : 브리지들이 루트 브리지로부터 헬로패킷을 받지 못하면, 이 시간동안 기다린 다음 스패닝 트리 구조 변경을 시작한다.
    - 포워딩 딜레이 : 브리지 포트가 블로킹에서 포워딩 상태로 넘어가기까지 걸리는 시간. 사실상 블로킹에서 포워딩으로 넘어가는 데 걸리는 시간은, 포워딩 딜레이의 두 배가 된다. (블로킹→리스닝 이후 딜레이만큼 기다린 다음 러닝으로, 러닝에서 다시 딜레이만큼 기다린 후 포워딩으로 가기 때문)
- 한 링크가 끊어졌을 때 STP를 이용해 다른 경로를 살리는 데 걸리는 시간은, 우리의 생각처럼 바로 살아나는 편은 아니다. 시간이 조금 걸릴 수 있다.

### VLAN
- 스위치의 기능 중 요즘 가장 많이 사용되는 가상 랜(VLAN)
- 예전에는 콜리전 영역을 나눠주는 정도만 해도 스위치 역할이 충분했으나, 이제 무언가 새로운 동작이 필요해졌다.
- VLAN을 사용하면 한 대의 스위치를 마치 여러 대의 분리된 스위치처럼 사용하고, 여러 개의 네트워크 정보를 하나의 포트를 통해 전송할 수 있다.

### VLAN에서 꼭 기억해야 할 몇 가지
- VLAN은 스위치에서 지원하는 기능이다. (허브나 브리지는 X)
- VLAN은 한 대의 스위치를 여러 개의 네트워크로 나누기 위해 사용한다. 따라서 스위치가 일단 VLAN으로 나누어지면, 나누어진 VLAN 간의 통신 오직 라우터를 통해서만 가능하다. (브로드캐스트 도메인이 나누어진 것것으로 서로 다른 네트워크이므로)
- 하나의 포트를 통해 서로 다른 여러 개의 VLAN을 전송할 수 있게 하는 포트를 트렁크 포트라고 한다.

### VLAN에서의 트렁킹과 VTP
- 각 스위치에 여러개 VLAN이 있으므로 각 VLAN별로 링크를 만들어주어야 하지만, 그러면 너무 많은 링크가 필요하므로 마치 `셔틀버스처럼 모든 VLAN이 하나의 링크를 통해 다른 스위치나 라우터로 이동하기 위해` 트렁킹이란 것을 만듬
- 즉 트렁킹은 `여러 개의 VLAN을 한 번에 전송하는 방식` 이다.
- 네이티브 VLAN : 패킷에 VLAN 정보를 붙이지 않고 보내는 VLAN. 모든 네트워크에서 유일하게 한 개의 VLAN만을 네이티브 VLAN으로 세팅 가능. IEEE 802.1Q 방식(트렁킹 표준 프로토콜)에 있는 VLAN이다.
- VTP : 스위치들 간에 VLAN 정보를 서로 주고받아 스위치들이 가지고 있는 VLAN 정보를 항상 일치시켜 주기 위한 프로토콜. 시스코만의 프로토콜인 ISL 방식에 있는 것이다.

**Comment by jjangsungwon** [comment]
## 스패닝 트리
- 스위치나 브리지에서 발생하는 루핑을 막아주기 위한 프로토콜
- 출발지부터 목적지가지 2개 이상의 경로가 존재할 때 1개의 경로만 남겨두고 나머지 모두 끊어두었다가, 사용하던 경로에 문제가 발생하면 끊어두었던 경로를 하나씩 살림

### Bridge ID
- 스위치 ID 라고 하지 않는 특별한 이유는 없음,,
- 스위치들이 통신할 때 서로를 확인하기 위해 하나씩 가지고 있는 번호
- 8바이트(64비트)로 구성. 앞의 2바이트(16비트)는 Bridge Priority, 뒤의 6바이트(48비트)는 맥 어드레스로 구성

### Path Cost
- 한 스위치에서 다른 스위치로 가는 데 드는 비용
- 낮은 값이 더 높은 우선순위를 가짐
- 소수점이 나오지 않도록 하기 위해 각 속도마다 정해진 Past Cost 값이 있음

### 스패닝 트리 프로토콜
- 첫째, 네트워크당 하나의 루트 브리지를 갖는다.
  - 낮은 BID를 갖는 브리지가 루트 브리지 
- 둘째, 루트 브리지가 아닌 나머지 모든 브리지는 무조건 하나씩의 루트 포트를 갖는다.
  - 루트 포트는 루트 브리지에 가장 가까이 있는 포트를 말한다. Past Cost 값을 활용하여 루트 포트를 찾는다. 
- 셋째, 세그먼트당 하나씩의 데지그네이티드 포트를 갖는다.
  - 루트 브리지까지의 Past Cost, 즉 세그먼트 상에서 Root Path Cost를 서로 비교해서 더 작은 Root Past Cost를 가진 포트가 데지그네이티드 포트로 선출된다.
  - 루트 브리지의 모든 포트들은 언제나 데지그네이티드 포트로 선정된다, 

### 스패닝 트리 프로토콜 순서 정하기
- 1단계: 누가 더 작은 Root BID를 가졌는가?
- 2단계: 루트 브리지까지의 Past Cost 값은 누가 더 작은가?
- 3단계: 누구의 BID(Sender BID)가 더 낮은가?
- 4단계: 누구의 포트 ID가 더 낮은가?
- BPDU(Bridge Protocol Data Unit): 스패닝 트리 정보를 주고받기 위해 사용하는 특수 프레임 (Root BID, Root Past Cost, Sender BID, Port ID 정보 등이 실려 있음)

### 스패닝 트리 프로토콜의 상태 변화
- `Disabled`: 포트 고장 혹은 ShutDown 상태
  - 데이터 전송 x
  - 맥 어드레스 배우기 x
  - BPDU 통신 x
- `Blocking`: 스위치 맨 처음 켜거나 Disabled 되어 있는 포트를 관리자가 다시 살렸을 때 블로킹 상태가 됨
  - 데이터 전송 x
  - 맥 어드레스 배우기 x
  - BPDU 통신 O
- `Listening`: 블로킹 상태에 있던 스위치 포트가 루트 포트나 데지그네이티드 포트로 선정되면 리스닝 상태로 넘어감
  - 데이터 전송 x
  - 맥 어드레스 배우기 x
  - BPDU 통신 O
- `Learning`: 리스닝 상태에 있던 스위치 포트가 포워딩 딜레이 디폴트 시간인 15초 동안 상태를 계속 유지하면 리스닝 상태에서 러닝 상태로 넘어감
  - 데이터 전송 x
  - 맥 어드레스 배우기 O
  - BPDU 통신 O
- `Forwarding`: 스위치 포트가 러닝 상태에서 다른 상태로 넘어가지 않고 포워딩 딜레이 디폴트 시간인 15초 동안 상태를 유지하면 러닝 상태에서 포워딩 상태로 넘어감
  - 데이터 전송 O
  - 맥 어드레스 배우기 O
  - BPDU 통신 O
- 리스닝, 러닝, 포워딩 상태에서 다시 블로킹 상태로 돌아갈 수 있음(루트 포트나 데지그네이티드 포트에서 탈락)
- 모든 포트에서 Disable 상태로 돌아갈 수 있음 (ShowDown 명령, 포트 고장)

### 스패닝 트리 변화
- `Hello Time`: 루트 브리지가 얼마 만에 한 번씩 헬로 BPDU를 보내는지에 대한 시간
- `Max Age`: 브리지들이 루트 브리지로부터 얼마 동안 헬로패킷을 받지 못했을 때 루트 브리지가 죽었다고 생각하고 새로운 스패닝 트리를 만들기 시작하는가에 대한 시간
- `Forwarding Delay`: 브리지 포트가 블로킹 상태에서 포워딩 상태로 넘어갈 때까지 걸리는 시간

## 맥 어드레스
- 활용: 스위치나 브리지가 출발지에서 들어오는 맥 어드레스를 보고 그것을 자신의 맥 어드레스 테이블에 저장한 후 그 주소 테이블에 있는 맥 어드레스를 찾으면 그쪽 포트로만 보내고 나머지 포트는 막아줌으로써 스위치의 콜리전 도메인을 막는 역할을 수행함
- 지정 방식
  - Dynamic(default): 300초(디폴트)가 지나면 맥 테이블에서 정보가 지워짐
  - Permanent: 절대 지워지지 않도록 맥 어드레스에 저장 

## Virtual LAN
- 한 대의 스위치를 마치 여러 대의 분리된 스위치처럼 사용하고, 또 여러 개의 네트워크 정보를 하나의 포트를 통해 전송할 수 있음 -> 하나의 스위치에 연결된 장비들도 브로드캐스트 도메인이 서로 다를 수 있음
- 스위치에서 지원하는 기능. 허브나 브리지에서는 지원 x
- 나누어진 VLAN 간의 통신은 라우터를 통해서만 가능

### 트렁킹
- 여러 개의 VLAN 들을 함께 실어나르는 것
- 각 스위치에 여러 개의 VLAN이 있기 때문에 원래는 각 VLAN 별로 링크를 만들어주어야 함. 하지만, 그렇게 구성하면 너무 많은 링크가 필요함. 이를 해결하기 위해서 모든 VLAN이 하나의 링크를 통해 다른 스위치나 라우터로 이동하기 위해 트렁킹이라는 것이 만들어짐
- ISL, IEEE 802.1Q(표준) 방식 존재
- 딱 하나의 VLAN만 이름표를 달지 않을 수 있음 (네티이브 VLAN)

### VTP
- 스위치들 간에 VLAN 정보를 서로 주고받아 스위치들이 가지고 있는 VLAN 정보를 항상 일치시켜 주기 위한 프로토콜
- 시스코만의 프로토콜
- 메시지 종류
  - `Summary Advertisement`: VTP 서버가 자기에게 연결되어 있는 스위치들에게 5분마다 한 번씩 전달하는 메시지. 자신이 관리하는 VTP 도메인의 구성에 대한 Revision 넘버를 보냄. Revision 넘버를 보고 자신들의 VLAN 정보가 최신 버전인지 판단 가능. Summary Advertisement는 VLAN 구성에 변화가 생겼을 때도 전달이 되는데, 이때는 5분을 기다리지 않고 즉시 전달
  - `Subset Advertisement`: VLAN의 구성이 변경되었을 때나 VTP 클라이언트로부터 Advertisement Request 메시지를 받았을 때 전송. 실제 VLAN 정보는 Subset Advertisement에 저장되어 전달
  - `Advertisement Request`: 클라이언트가 VTP 서버에 Summary Advertisement와 Subset Advertisement를 요청하는 용도로 사용됨. 클라이언트는 자신의 Revision 넘버보다 더 높은 Revision 넘버를 갖는 Summary Advertisement를 전달받거나, VTP 도메인 이름이 바뀌거나, Subset Advertisement 메시지를 잃어버렸거나, 스위치가 새로 리셋되었을 경우 Advertisement Request 메시지를 VTP 서버에 보냄
- 모드
  - VTP 서버 모드: VLAN 생성, 삭제, 이름 수정, 정보 전송
  - VTP 클라이언트 모드: 전달
  - VTP 트랜스페어런트: 자신의 정보 업데이트 후 다른 스위치에게 전송 x, 전달 역할은 수행
