### ISSUE TITLE
7. 라우터만 알면 네트워크 도사? (1)

### ISSUE THREAD

**Issue by hhhyunwoo** [WhiteKow/hoony-easy-written-cisco-networking-study#5]

**Comment by ChanhuiSeok** [comment]
## 라우터란
- 브로드캐스트 영역을 나눠주기 위해 꼭 필요함. 지능을 가진 경로 배정기
- 단, 라우터에 직접 세팅을 해 주어, 인터넷 사이트를 찾아가는 데이터를 목적지까지 가장 빠르고 효율적인 길을 스스로 찾아 안내할 수 있게 해야 한다.

## 라우터는 무슨 일을 할까
- 라우터는 경로 결정과 스위칭의 역할을 한다.
- 경로 결정 : 데이터 패킷이 목적지까지 갈 수 있는 길을 검사하고, 어떤 길로 가는 것이 가장 적절한지 결정하는 것
- 스위칭 : 위의 그 길이 결정되면, 그쪽으로 데이터 패킷을 스위칭해 줌 (스위치가 하는 일과 다름에 주의)
- 라우터가 가장 좋은 길을 찾아가는 방법은 **라우팅 알고리즘(라우팅 프로토콜)**이 사용됨. 이 때 라우팅 테이블이라는 것을 만들어 관리한다. 이를 위해 라우터는 PC처럼 CPU, 메모리, 인터페이스 등을 가지고 있다.
    - 인터페이스란? 라우터에 나와있는 접속 가능한 포트를 말한다.
- 시스코에서는 라우터에 들어가는 소프트웨어를 IOS(Internetwork Operating System)라고 하고 이에 따라 가격 차이도 꽤 많이 남

## 라우팅 프로토콜(라우팅 알고리즘), 라우티드 프로토콜
- TCP/IP, IPX, AppleTalk 등 **우리가 아는 모든 프로토콜은 라우티드 프로토콜**임. 즉, 라우팅을 당하는, 라우터가 라우팅을 해 주는 고객을 의미
- **라우팅 프로토콜은 라우티드 프로토콜들에게 목적지까지 가장 좋은 길을 갈 수 있게 해주는 역할**을 함
- 즉, 라우터는 어떤 라우팅 프로토콜을 채용하는가에 따라 라우터의 성능이 결정된다고 볼 수 있다. (기본 라우터 성능도 중요)
- 라우팅 알고리즘은 자신의 라우팅 테이블을 가지고, 자기가 찾아갈 경로에 대한 정보를 이곳에 기억해 둔다. (어디가 가장 빠르고 안전한 길인지?) 주로 목적지와 목적지까지의 거리, 어떻게 가는지 등의 내용이 들어간다. 끊임없이 내용이 변화할 수 있다.

## 스태틱, 다이내믹 라우팅 프로토콜
- 스태틱 라우팅 프로토콜
    - 장점 : 라우터에 사람이 일일이 경로를 입력해주는 것. 가장 빠르고 좋은 길을 사람이 찾아서 입력한다. 라우터에 부담이 들지 않아 라우팅 속도가 빨라져 성능이 좋아진다.
    사람이 경로를 직접 입력하므로 라우터들끼리 라우팅 테이블을 교환할 필요도 없고, 네트워크 대역폭 절약이 가능하고, 외부에 자신의 정보를 알리지 않으므로(교환하지 않으므로) 보안에도 강하다.
    - 단점 : 귀찮다. 그리고 입력해준 경로에 문제가 생기면 큰 일이 발생한다.
- 다이내믹 라우팅 프로토콜
    - 장점 : 설정했던 경로에 문제가 생기면 알아서 판단하여 그때그때 좋은 길을 찾아내고, 사람이 직접 경로 입력을 해 줄 필요가 없다.
    - 단점 : 라우터에 부담을 준다. 라우터가 할 일이 많아지기 때문이다. RIP, IGRP, OSPF, EIGRP 등이 다이내믹 라우팅 프로토콜이다.

## 라우팅 테이블, AS, 내부 및 외부용 라우팅 프로토콜
- 라우터는 전원을 켜는 순간부터, 라우팅 테이블을 만들기 시작하여 어떤 패킷이 길 안내를 요청하면 라우팅 테이블을 보고 길을 안내한다. **단, 전원이 꺼지면 모두 지워지게 된다.** 전원이 켜지면 다시 만들 수 있다.
- AS(Autonomous System) : 하나의 네트워크 관리자에 의해 관리되는 라우터들의 집단. 쉽게 말해 한 회사나 기업 또는 단체의 라우터 집단이다. AS라는 그룹으로 묶는 이유는, 라우터가 갖는 정보를 효율적으로 관리하고, 인터넷 서비스를 좀 더 간편하게 제공하기 위해서이다.
- AS 밖으로 나갈 때는 그 AS에 있는 문지기 라우터(ASBR)에게 정보를 묻고, 밖으로(인터넷) 나간다.
- 문지기 라우터는 자신의 AS와 인접해 있는 다른 AS에 대한 정보를 가지고 있으면서, 자기 AS에서 밖으로 나가는 라우터나 외부 AS에서 자기 AS쪽으로 들어오는 라우터에게 정보를 제공한다. 그러므로 라우터들은 전 세계 모든 네트워크에 대한 정보를 다 가지고 있을 필요 없이, 자신이 속한 AS에 대한 정보만 가지면 된다.
- 라우터가 AS 내부에서 사용하는 라우팅 프로토콜을 IRP 혹은 IGP라 하고, AS 간에 외부에서 사용하는 프로토콜은 ERP 혹은 EGP 라고 한다. (요즘은 EGP보다는 BGP를 많이 씀)

**Comment by jjangsungwon** [comment]
### 라우터란
- 네트워크 하는 사람이 가장 자주 만나는 장비: 인터넷을 사용하기 위해서, 서로 다른 네트워크 간 통신하기 위해서, 브로드캐스트 영역을 나눠주기 위해서
- 경로 결정과 스위칭 수행 
  - 가장 좋은 경로를 결정하기 위해서 라우팅 알고리즘 사용
  - 라우팅 알고리즘은 라우팅 테이블을 만들어서 관리

### 라우팅/라우티드 프로토콜
- 라우팅 프로토콜: 라우티드 프로토콜들에게 목적지까지 가장 좋은 길을 갈 수 있게 해주는 역할
- 라우티드 프로토콜: 라우팅을 당하는, 즉 라우터가 라우팅을 해주는 고객을 의미
- 라우팅 프로토콜을 다른 말로는 라우팅 알고리즘이라고도 한다. 라우팅 알고리즘은 자신의 라우팅 테이블을 가지고 있으면서 자기가 찾아갈 경로에 대한 정보를 저장한다.
  - 라우팅 테이블에는 목적지, 목적지까지의 거리, 어떻게 가야 하는가 등의 내용이 있음. 시간이 지나면서 계속 업데이트 수행.

### 스태틱/다이내믹 라우팅 프로토콜
- 스태틱 라우팅 프로토콜
  - 정해진 길만을 가기 때문에 일이 없는 대신 사람이 일일이 구성을 해줘야 하고, 정해진 길에 문제가 생기면 사람이 고쳐줄 때까지 계속 그 길로 가려고 함
  - 라우터 자체의 부담이 적고 메모리도 적게 사용함. 다른 라우터들과 데이터를 교환할 필요가 없어서 네트워크 대역폭 절약도 가능하고 보안에도 강함
- 다이내믹 라우팅 프로토콜 
  - 라우터가 알아서 가장 좋은 길을 찾아감
  - 스태틱에 비해서 라우터 부담이 많고 주기적인 업데이트가 필요하다는 단점이 있음
  - 하지만 여러 가지 상황에 자동으로 대응할 수 있다는 큰 장점이 있음

### 라우터 모드
- 유저모드: 현재 상태를 볼 수 있음. 라우터 구성 변경 x
- 프리빌리지드(운영자 모드): 모든 라우터의 명령 가능 (구성 파악, 변경 가능)
- 구성 모드(Config 모드): 라우터의 구성 파일 변경하는 모드. 프리빌리지드 모드에서만 접속 가능
- 셋업 모드: 라우터를 처음 구매해서 켰거나 라우터에 구성 파일이 없는 경우 라우터가 부팅하면서 자동으로 들어가는 모드
- RXBOOT 모드: 라우터의 패스워드를 모르는 경우나 라우터의 이미지 파일에 문제가 생긴 경우 복구를 위해 사용 (거의 사용 x)

**Comment by hhhyunwoo** [comment]
# 7. 라우터만 알면 네트워크 도사? (1)

## 라우터란?

- 지능을 가진 `경로 배정기`
- 라우터는 자신이 가야 할 길을 자동으로 찾아서 갈 수 있는 능력이 있음
- 라우터의 기능 (`가장 좋은 길을  찾는 것`) 을 위해서 PC 처럼 CPU, Memory, Interface 등을 가지고 있음

## 라우터가 하는 일

### Path Determination

- 데이터 패킷이 목적지까지 갈 수 있는 길을 검사하고 `어떤 길로 가는 것이 가장 적절`한지를 결정함

### Switching

- `Path determination` 을 통해 경로가 결정되면 그 쪽으로 데이터 패킷을 `스위칭`해줌

## Routing Protocol & Routed Protocol

### Routing Protocol

- 라우터가 `자동차`라고 치면, 그 자동차를 안전하고 빠르게 운전하는 `운전기사`라고 볼 수 있음
- `라우팅 알고리즘`이라고도 함
- ex. RIP, IGRP, OSPF, EIGRP 등이 있음

### Routed Protocol

- TCP/IP, IPC, AppltTalk 등 우리가 아는 모든 프로토콜은 전부 `라우티드 프로토콜`이다.
- 라우터가 라우팅을 해주는 고객을 의미함. 즉, `말 그대로 라우팅을 당하는 주체`
    - 라우터라는 자동차에 타는 승객!

즉, 라우터 입장에서는 어떤 라우팅 프로토콜을 채용하는가에 따라서 `라우터의 성능`이 결정됨. 물론 라우터 자체의 성능 또한 중요함 

### Static Routing Protocol

- 라우터에 사람이 `일일이 경로를 입력`해줘야 함
- `Pros`
    - 시키는 대로 하기 떄문에 라우터 자체에 부담이 들지 않아 `속도도 빠르고 성능이 좋아짐`
    - 다이나믹 라우팅 방식처럼 라우팅 테이블을 교환할 필요가 없음. 따라서 `네트워크 대역폭을 그만큼 절약`할 수 있음
    - 보안에 강함
- `Cons`
    - 사람이 일일이 경로를 넣어줘야하는 것이 `귀찮음`
    - 입력해준 경로에 문제가 생기면 경로를 다시 고쳐주기 전까지 문제가 있는 쪽으로 데이터를 보내려고 함

### Dynamic Routing Protocol

- 상황에 따라서 그떄 그떄 변화가 가능한 프로토콜
- `Pros`
    - 여러 상황에 자동으로 대응이 가능함
- `Cons`
    - 라우타가 할 일(Path 계산, 정보 갱신 확인)이 많기 때문에 라우터에 `부담을 줌`

→ 라우팅 성능을 높이기 위해 스태틱을 사용하기도 하고, 라우터가 선택할 수 있는 경로가 오직 하나뿐일 때는 다이나믹 프로토콜을 쓸 필요가 없음 

## Routing Table

- 라우팅 프로토콜이 있으면서 어떤 길이 가장 좋은 길인지 메모해 두는 일종의 `이정표` 같은 것
- 라우팅 알고리즘은 자신의 라우팅 테이블을 가지고 있으면서 자기가 찾아갈 경로에 대해 정보를 이곳에 `기억해둔다.`

![image](https://user-images.githubusercontent.com/37402136/210921335-6b86d84e-59b0-4ac2-9510-afd234b109f7.png)

- 라우팅 테이블은 라우터의 `RAM`에 저장됨
    - `전원이 껐다 켜지면 날라감`
    - 하지만, 라우팅 테이블은 그때 그때 변화하는 다이나믹한 정보이고, 라우팅 테이블을 다 지운 상태에서도 라우터가 이 테이블을 다시 만드는 데는 몇 초 정도 밖에 걸리지 않기 때문에 저장하지 않아도 됨
    - Q) 그러면 스태틱 라우팅 프로토콜은?

## AS, 그리고 내부용과 외부용 라우팅 프로토콜

### Autonomous System (AS)

- `Autonomous System`
- 하나의 네트워크 관리자에 의해서 관리되는 라우터들의 집단. 즉, 한 회사나 기업 또는 단체의 `라우터 집단을 의미`
- AS 라는 그룹으로 묶어주는 이유는 라우터가 가지는 정보를 `효율적으로 관리하고 인터넷 서비스를 좀 더 간편하게 제공하기 위함`
- AS 밖으로 나갈 때는 그 AS에 있는 `문지기 라우터` (`ASBR`: Autonomous System Boundary Router) 에게 정보를 물어봐서 밖으로 (인터넷) 나감
    - 즉, 이런 시스템 때문에 라우터들은 인터넷에 접속하더라도 전 세계의 모든 네트워크에 대한 정보를 다 가지고 있을 필요가 없고, `단지 자신이 속한 AS에 대한 정보만 가지면 됨`

![image](https://user-images.githubusercontent.com/37402136/210921358-13432784-49cb-4fc5-ad48-6813db373d75.png)

### Interior Routing Protocol (IGP : Interior Gateway Protocol)

- AS `내부에서 사용하는 라우팅 프로토콜`
- RIP, IGRP, EIGRP, OSPF

### Exterior Routing Protocol (EGP : Exterior Gateway Protocol)

- AS `외부에서 서로 라우팅 정보를 주고 받기 위해 사용하는 프로토콜`
- EGP, BGP

## 라우터 구성 방법

1. 맨 처음 라우터를 구성할 떄 쓰는 `콘솔 케이블`을 통한 구성
2. 원격지에서 `모뎀을` 이용한 구성
3. IP주소가 세팅된 후 네트워크를 통해서 접속하는 `텔넷을` 이용한 구성
4. 네트워크 관리 시스템이 있는 곳에서 사용하는 `NMS` 를 이용한 구성
5. 미리 구성된 파일을 저장했다가 나중에 라우터로 다운로드하는 `TFTP` 서버를 이용한 구성

## 라우터의 모드

### RXBOOT

- 라우터의 패스워드를 모르는 경우나 라우터의 이미지 파일에 문제가 생긴 경우 복구를 위해 사용함

### Setup

- 라우터를 처음 구매해서 파워를 켰거나 라우터에 구성 파일이 없는 경우 라우터가 부팅하면서 자동으로 들어가는 모드

### User

- `꺽쇠` (>) 로 프롬프트가 나오면 유저모드임
- 현재상태를 볼 수 있고, 테스트가 가능함
- 하지만 라우터의 구성 파일을 본다거나 구성 자체 변경은 불가

### Privileged

- `enable` 명령어로 들어갈 수 있음
- 꺽쇠 (>) 가 아니고 `#` 으로 프롬프트가 나오면 프리빌리지드 모드임
- 명령의 제약이 없는 모드이다.

### Configuration

- 라우터의 `구성파일을` 변경하는 경우에 사용하는 모드
- 프리빌리지드 모드에 있어야 접근 가능함
- enable 후 `config terminal` 명령어로 접근 가능

## 라우터의 구성요소

### 내부

![image](https://user-images.githubusercontent.com/37402136/210921397-a8b37f98-d439-44bc-ab50-0841b771470a.png)

- RAM
    - 파워가 켜진 다음에 `RAM 위로 운영체제가 올라옴`
        - 시스코 라우터는 IOS 라는 운영체제를 사용함
    - `라우팅 테이블`이 들어감
    - `구성 파일`이 올라감
    - 이외에도 `ARP 캐시`, `패스트 스위칭에 대한 캐시` 등이 들어감
- NVRAM
    - `RAM 백업`을 위해 사용됨
    - `라우터의 구성파일`은 매우 중요하기 때문에 백업을 진행 함
- Flash Memory
    - `IOS 운영체제`가 저장됨
    - NVRAM과 다른 점은 NVRAM에 비해서 용량이 큼
        - NVRAM은 구성파일 저장용으로만 사용되지만, 플래시 메모리는 주로 IOS 이미지 파일 저장용으로 사용 됨
    - `IOS 는 전원이 켜지면서 라우터의 램으로 뛰어올라옴`
- ROM
    - 파워가 켜지면 `어떤 순서`로 라우터 스스로의 상태를 점검하고 또 어디서 운영체제를 가져다가 메모리에 올릴 것인지 등을 적어 둠

### 외부
![image](https://user-images.githubusercontent.com/37402136/210921413-35bd5505-ab56-48c0-a538-516e95a47511.png)
