### ISSUE TITLE
7. 라우터만 알면 네트워크 도사? (2)

### ISSUE THREAD

**Issue by hhhyunwoo** [WhiteKow/hoony-easy-written-cisco-networking-study#6]

**Comment by hhhyunwoo** [comment]
# 7. 라우터만 알면 네트워크 도사? (2)

## 라우터 셋업 모드

- `Set up` 방식

## 라우터에 명령을 입력하는 두 번째 방법

- `Configuration` 모드
- `configure terminal`
    - 라우터의 구성을 콘솔이나 텔넷을 이용해서 할 때 사용하는 모드
- 라우터의 구성 변경을 위해서는 항상 `privileged` 모드에서 구성 모드로 들어가야하는데, privileged 모드에서 구성 모드로 들어가기 위한 명령은 `configure` 이다.
- 또 구성을 텔넷이나 콘솔로 하는 경우에는 teminal 이라는 옵션을 사용해서 `configure terminal` 을 사용한다.
- 모든 변경을 마치고 빠져 나올 때는 `ctrl + z` , RAM의 구성 파일을 NVRAM으로 저장할 때는 `write memory` or `copy runningconfig startup-config` 명령 입력

## Static 라우팅을 이용한 Router 구성

- `Static` 라우팅
    - 경로를 직접 넣어주기 때문에 라우팅이 빠르게 가능
    - `라우팅 테이블`도 적게 사용함
    - 경로에 문제가 생기면 다른 길을 찾아내지 못하고, 수정해줄 때까지 기다림
    - → 갈 수 있는 경로가 하나밖에 없는 `Stub 라우터 용`으로 많이 사용됨
        - `Stub 네트워크` : 오직 하나의 경로만을 통해서 외부 망과 연결된 네트워크를 의미

### 스태틱 라우팅만 알면 디폴트 라우트는 식은 죽 먹기

- `Default` 라우팅
    - 경로를 찾아내지 못한 모든 네트워크들은 모두 이곳으로 가라고 `미리 정해 놓은 길`
    - 디폴트 라우트를 잡아놓으면 다른 경로에서 해당 네트워크를 못 찾을 때는 무조건 인터넷 쪽 인터페이스로 가보게 되는 것
- Default 라우트 만드는 법
    1. 디폴트 네트워크를 이용
    2. 스태틱 명령을 이용

<img width="837" alt="image" src="https://user-images.githubusercontent.com/37402136/214020188-a24bc595-d336-4ecf-9e9f-b1cdfaea3870.png">

<img width="837" alt="image" src="https://user-images.githubusercontent.com/37402136/214020188-a24bc595-d336-4ecf-9e9f-b1cdfaea3870.png">

## Distance Vector 와 Link state

- 라우터는 스태틱 라우팅 프로토콜 / 다이나믹 라우팅 프로토콜로 나뉘었음
- 또 하나의 라우팅 프로토콜에 대한 분류가 `distance vetor` 와 `link state` 이다

### Distance vector

- `거리`와 `벡터`만을 위주로 만들어진 라우팅 프로토콜
- 한 라우터가 모든 라우팅 정보를 가지고 있을 필요가 없기 때문에 라우팅 테이블을 줄일 수 있어서 메모리를 절약하고, 구성 자체가 간단하여 여러 곳에서 `표준으로 사용`되고 있음
- 정해진 시간마다 한 번씩 꼭 라우팅 테이블의 업데이트가 일어나기 때문에 트래픽을 낭비하고 `Convergence Time`이 너무 느림
- → 커다란 네트워크에서는 적용하지 않고 `규모가 작은 네트워크`에 적용할 경우 장점을 살릴 수 있음
- `RIP`(Routing Information Protocol), `IGRP`(Interior Gateway Routing Protocol)

### Link state

- 한 라우터가 목적지까지의 `모든 경로 정보`를 다 알고 있음
- 링크에 대한 정보(어디에 어떤 네트워크가 있고, 거기까지 가려면 어떤 라우터를 통해야 한다는 정보) 를 `토폴러지 데이터베이스`로 만들게 됨
- 토폴러지 데이터베이스를 가지고 `SPF`(Shortest Path First) 라는 알고리즘을 계산 후 SPF 트리를 만듬
- 한 라우터에서 목적지까지의 모든 경로를 알고 있기 때문에 중간에 링크의 변화가 생겨도 이를 알아내는 데 걸리는 시간이 짧음.
- 라우팅 테이블 교환이 자주 발생하지 않고 `트래픽 발생을 줄여줌`
- 라우팅 정보를 관리해야 하기 때문에 메모리 많이 소모, `CPU가 일을 많이 함`
- → `고용량 라우터`에 적용하는 것이 바람직함
- `OSPF`(Open Shortest Path First)

## Telnet 을 이용한 장비 접속

- `Telnet`
    - 기본적으로 TCP/IP 위에 올라가는 프로그램

## Ping 과 Trace

- `핑`과 `트레이스`는 라우터를 구성한 후 네트워크의 연결에 이상이 없는지를 테스트하기 위해 만든 프로그램
    - 즉, 출발지에서 목적지까지 연결에 이상이 없는지, 그리고 이상이 있다면 어디에서 이상이 발생했는지를 핑과 트레이스를 이용해서 찾아낼 수 있음

### Ping

- 단순 핑의 경우 에코 패킷의 출발지를 정할 수 없기 때문에 PC에 가서 직접 핑을 해보지 않는 이상 확인해볼 수 있는 방법이 없음.
- 확장형 핑
    - 에코 패킷의 출발지를 지정
    - 에코 패킷의 크기
    - 핑을 몇 번 보낼 것인가

### Trace

- 출발지에서 목적지 뿐만 아니라 중간에 거친 경로에 대한 정보와 소요 시간까지도 확인해볼 수 있는 것이 Trace 명령

**Comment by ChanhuiSeok** [comment]
**라우터 셋업 모드**
- 라우터 구성 파일 만들기
- 라우터는 이후 자동으로 configuration file을 자동으로 만들고, 사용할지 말지 저장 여부를 선택하게 한다. 이 구성파일이 저장되면 이후 라우터를 껐다가 켜도 셋업 모드로 들어가지 않는다.

**라우터 구성 모드**
- 셋업 모드는 시간만 많이 걸리고, 막상 셋업하고 싶은 명령은 없는 경우가 있어 잘 쓰이지 않음
- 대부분의 경우는 Configuration 모드에서 작업한다.
- configure termial : 라우터 구성을 콘솔이나 텔넷을 이용해서 할 때 사용하는 모드 (터미널 앞에 사람이 직접 앉아서 명령을 하나하나 입력해 주는 모드)
- configure memory : NVRAM에 있는 백업 구성 파일을 현재 RAM에서 동작하고 있는 구성 파일 위에 덮어씌워서, 현재 돌아가고 있는 파일 대신 백업 파일을 사용하겠다는 의미의 명령

**스태틱 라우팅을 이용한 라우터 구성**
- 스태틱 라우팅 프로토콜 : 운영자가 직접 경로를 입력해주므로 라우터는 라우팅하는데 머리를 쓰지 않아 빠르게 라우팅 가능, 라우팅 테이블도 적게 사용한다는 장점도 있음. 단점은 입력해준 경로에 문제가 생겨도 다른 길을 자동으로 찾아내지 못함
    - 따라서 스태틱 라우팅 프로토콜은 갈 수 있는 경로가 하나밖에 없는 Stub 라우터용으로 많이 사용
    - **Stub** 네트워크 : 오직 하나의 경로만을 통해 외부 망과 연결된 네트워크 (예: 게임방 네트워크)

**디폴트 라우트**
- 경로를 찾아내지 못한 모든 네트워크들은 모두 이곳으로 가라고 미리 정해 놓은 길
- 스태틱 라우팅과의 차이점
    - 스태틱 라우팅은 그냥 특정 목적지를 가기 위한 구성
    - 디폴트 라우팅은 특정 목적지를 지정하지 않고 그냥 모든 목적지가 모두 디폴트로 지정한 곳으로 감

**디스턴스 벡터, 링크 스테이트**
- 라우팅 프로토콜에는 다이내믹과 스태틱이 있다.
- 라우팅 테이블을 어떤 식으로 관리하는가에 따른 분류 - 디스턴스 벡터, 링크 스테이트 알고리즘
- 디스턴스 벡터 알고리즘 : 거리와 방향만을 위주로 만들어진 라우팅 알고리즘, 목적지까지의 모든 경로를 자신의 라우팅 테이블 안에 저장하는 것이 아니고, 목적지까지의 거리와 목적지까지 가기 위해 어떤 인접 라우터를 거쳐야 하는지 방향만을 저장. → 인접 라우터들과 주기적으로 라우팅 테이블을 교환해 자신의 정보에 변화가 생기지 않았는지 확인 및 관리함
    - 장점 : 한 라우터가 모든 라우팅 정보를 가지고 있을 필요 없음 → 라우팅 테이블을 줄일 수 있어 메모리 절약 가능. 라우팅 구성이 간단하며, 여러 곳에서 표준으로 사용되고 있음
    - 단점 : 라우팅 테이블에 아무런 변화가 없어도 정해진 시간마다 업데이트가 일어나므로 쓸데없이 트래픽을 낭비하고, 라우팅 테이블에 변화가 생기면 이 변화를 모든 라우터가 알때까지 걸리는 시간이 너무 느리다(Convergence Time).
- 링크 스테이트 알고리즘
    - 장점 : 한 라우터에서 목적지까지의 모든 경로를 알고 있으므로 중간에 링크의 변화가 생겨도 알아내는 데 걸리는 시간이 짧다. 라우팅 테이블의 교환도 자주 발생하지 않고, 교환이 일어나더라도 테이블에 변화가 있는 것만 교환하므로 트래픽을 줄여준다.
    - 단점 : 모든 라우팅 정보를 관리해야 해서 메모리를 많이 소모하고, SPF(Shortest Path First) 계산 등 여러 계산을 해야 해서 CPU가 일을 많이 해야 한다. 그러므로 커다란 네트워크에 설치되는 고용량 라우터에 적용되는 것이 바람직하다.

**핑과 트레이스**
- 라우터 구성 후, 네트워크의 연결에 이상이 없는지 테스트하고자 만든 프로그램. 즉, 출발지-목적지까지의 연결에 이상이 없는지, 이상이 있으면 어디에서 발생했는지 찾아낼 수 있다.
    - 핑에서 단순형 핑은 출발지 주소는 라우터를 떠나는 쪽 인터페이스로 자동으로 잡혀서, 출발지 주소를 변경해 주려면 반드시 확장형 핑을 사용해야 한다.
        - 확장형 핑은 ping 명령만 입력하고 엔터를 누른 뒤 나오는 질문에 하나씩 입력을 하는 방식으로 진행한다.
    - 트레이스는 목적지까지의 경로를 하나하나 분석해 준다. TTL이라는 값을 하나씩 증가시키면서 돌아오는 에러 메시지를 가지고 경로를 확인해 주는 기능을 제공

**Comment by jjangsungwon** [comment]
## 라우터 셋업 모드
- 라우터에 어떤 구성도 되어있지 않다면 부팅 후에 바로 셋업(setup) 모드로 들어간다.
- 셋업 모드는 라우터에 어떤 구성 파일도 저장되어 있지 않을 때 라우터가 이를 인식하고 자동으로 들어가는 모드이고, 이 모드에서는 질문과 답변을 통해서 라우터가 자동으로 구성 파일을 만든다.
- configure terminal을 이용해서 세팅을 주로 하기 때문에 셋업 모드는 자주 사용하지 않는다.

## 구성 모드
- 셋업 모드는 시간이 많이 걸리고 셋업하고 싶은 명령이 없는 경우가 있기 때문에 구성 모드를 자주 사용한다.
- 구성 모드에서는 명령 줄을 입력하자마자 명령이 효과를 발휘한다.

## 스태틱 라우팅
- 스태틱 라우팅 프로토콜은 라우터 운영자가 직접 경로를 입력한다.
  - 장점: 빠른 라우팅, 라우팅 테이블 적게 사용
  - 단점: 경로에 문제가 생기면 운영자가 수정할 때까지 기다려야한다. -> 경로가 하나밖에 없는 Stub 라우터용으로 자주 사용

## 디폴트 라우트
- 디폴트 라우트: 경로를 찾아내지 못한 모든 네트워크들은 모두 이곳으로 가라고 미리 정해 놓은 길
- 디폴트 네트워크 혹은 스태틱 명령을 이용해서 디폴트 라우트를 만들 수 있다.

## 디스턴스 벡터(Distance Vector)와 링크 스테이트(Link State)
- 디스턴스 벡터: 거리와 방향만 유지하며 라우터는 이웃 라우터와 주기적으로 라우팅 테이블을 교환한다.
  - 장점: 메모리 적게 들고 구성이 쉬움
  - 단점: 링크 변동 시 인식 시간이 길고 네트워크 크기(홉카운트)에 제한이 있음
- 링크 스테이트: 라우터가 목적지까지의 모든 경로를 알고 있음
  - 장점: 링크 변동 인식이 빠르고, 라우팅 테이블의 교환 주기가 길며, 교환 시에도 링크 변동이 일어난 라우팅 테이블만 교환하기 때문에 트래픽이 적음
  - 단점: 메모리의 소모가 많고 CPU의 로드가 많다.

## CDP
- CDP(Cisco Discovery Protocol)은 시스코 장비와 직접 연결된 시스코 장비를 찾아내는 프로토콜

## 텔넷
- 구성 변경이나 상태 점검에 사용된다.
- TCP/IP 위에 올라가는 프로그램이기 때문에 라우터나 스위치에는 TCP/IP가 설치되어 있어야 하고 IP 주소를 알고 있어야 한다.
- 그리고 시스코 장비에서 상대편으로 텔넷을 하려면 VTY 패스워드를 알고 있어야 한다.

## 핑과 트레이스
- 핑과 트레이스는 라우터를 구성한 후 네트워크의 연결에 이상이 없는지를 테스트하기 위해 만든 프로그램이다. 출발지에서 목적지까지 연결에 이상이 없는지, 그리고 이상이 있다면 어디에서 이상이 발생했는지 찾아낼 수 있다.
- 핑: 단순형 핑을 사용하면 출발지 주소는 항상 라우터를 떠나는 인터페이스가 된다. 확장형 핑을 사용하면 출발지 지정, 에코 패킷의 크기 등의 설정이 가능하다.
- 트레이스: 핑을 사용하면 중간에 거친 경로는 파악할 수 없는데 트레이스는 중간에 거친 경로에 대한 정보와 소요 시간까지도 확인할 수 있다.
