### ISSUE TITLE
8. 라우팅 프로토콜과의 한판

### ISSUE THREAD

**Issue by hhhyunwoo** [WhiteKow/hoony-easy-written-cisco-networking-study#7]

**Comment by hhhyunwoo** [comment]
# 8. 라우팅 프로토콜과의 한판

## RIP 라는 라우팅 프로토콜에 대한 이야기

### RIP (Routing Information Protocol)

- 라우팅 프로토콜
- 다이내믹 프로토콜
- 내부용 라우팅 프로토콜(IGP)
- 디스턴스 백터 알고리즘
- 라우터가 좋은 길을 경정하는 기준이 되는 요소 → Hop 카운트
- 디폴트 라우팅 업데이트 주기 → 30초

### RIP 장 단점

- 장점
    - 표준 라우팅 프로토콜
    - Configuration의 간단함
    - 메모리를 적게 사용함
- 단점
    - 홉 카운트만 가지고 경로를 선택하다 보니 실수를 많이 함
    - 자신의 라우터에서 15개 이상의 라우터를 거치는 목적지의 경우는 Unreachable 로 정의하고 데이터를 보내지 못함. → 커다란 네트워크 상에서 사용하기엔 무리

## Distance-Vector 라우팅 알고리즘에서의 문제점과 해결책

- 한번 배운 라우팅 테이블을 계속 전달하기 때문에 업데이트가 모든 네트워크에 전달되는 시간(Convergence Time)이 많이 걸림.
    - → Looping 이 발생할 수 있음
- 해당 문제를 해결하기 위한 대책들
    - Maximum Hop Count
        - 최대 홉 카운트를 정해놓으면 루핑이 발생하더라도 멈출 수 있음
    - Hold Down Timer
        - 어떤 경로가 죽었다고 판단하면 이 경로에 대한 상태를 바로 바꾸지 않고 일정 시간이 지난 다음에 바꾸겠다는 것
    - Split Horizon
        - 라우팅 정보가 들어온 곳으로는 같은 정보를 내보낼 수 없다는 것
    - Route Poisoning
        - 라우팅 테이블에 극약 처방
        - 네트워크 A가 다운되면 라우터가 네트워크 A에 대한 메트릭 값을 16으로 바꾸면서 사용할 수 없게 만들어버림
    - Poison Reverse
        - 라우팅 정보를 되돌려 보내기는 하되, 이 값을 무한대 값으로 쓰는 방식
- 디스턴스 벡터 알고리즘은 쉽고, 간편하고, 라우팅 테이블을 적게 사용하는 등 여러가지 장점이 있지만, 루핑이 발생하기 쉬움.

## IGRP 라우팅 프로토콜

- Interior Gateway Routing Protocol
- 다이내믹 프로토콜
- 내부용 라우팅 프로토콜 (IGP)
- 디스턴스 벡터 알고리즘
- 모든 라우터에서 전부 사용 가능한 프로토콜은 아님
- 다섯 가지 요인을 가지고 가장 좋은 경로를 선택함
    - Bandwidth
    - Delay
    - Reliability
    - Load
    - MTU (Maximum Transmission Unit)
    - → Hopt 카운트만 가지고 목적지를 찾는 RIP 와는 달리 좀 더 지능적으로 경로를 선택할 수 있음

### PPS

- Packet Per Second
- PPS = 1 sec / (IFG + Preamble Time + Frame Time)
- IFG : Inter Frame Gap
- Preamble Time : 프레임 앞에 붙는 서두
- Frame Time : 프레임이 날아가는 시간

## OSPF 라우팅 프로토콜

- Open Shortest Path First

**Comment by ChanhuiSeok** [comment]
## RIP 라우팅 프로토콜
- 다이내믹 라우팅 프로티콜, 내부용 라우팅 프로토콜, 디스턴스 벡터 알고리즘을 채택
- 라우터가 좋은 길을 결정하는 기준 → 홉 카운트
- 최대한 갈 수 있는 홉 카운트의 거리는 15개까지이다.
- 디폴트 라우팅 업데이트 주기는 30초
- RIP는 예전부터 많이 사용된 표준 라우팅 프로토콜이고 메모리를 적게 사용하는 장점이 있으나, 목적지까지 최적 경로를 찾아가는 방법을 알아봐야 한다. 목적지까지 가는 데 네트워크를 몇 번 거쳐야 하는가를 홉 카운트라고 하며, RIP는 가장 낮은 홉 카운트가 가장 좋은 경로이다. (오로지 홉 카운트에 의존)

## Administrative Distance
- 한 라우터에서 라우팅 프로토콜을 2개씩 쓰는 경우가 생길 수 있음. 어떤 경로 정보를 예를 들어 RIP, IGRP에서 동시에 받는다면, 어떤 라우팅 프로토콜에서 온 정보를 이용해서 경로를 찾을까 하는 것이다. 그리고 그것을 Administrative Distance 값을 보고 판단할 수 있다.
- 이 때는 디스턴스 값이 작은 쪽의 것을 선택하면 된다. (라우터가 직접 가지고 있는 인터페이스, 스태틱 라우트 명령을 준 경우 등에는 디스턴스 값이 0이 됨)

## Distance-Vector 라우팅 알고리즘의 문제점과 해결책
- 문제점 : 시간 → 한 번 배운 라우팅 테이블을 계속 전달하므로 업데이트가 모든 네트워크에 전달되는 시간이 많이 걸리므로, 루핑 발생 가능
    - 한 라우터가 라우팅 정보에 대한 모든 정보를 가지고 있지 못하며, 이웃 라우터로부터의 업데이트가 느리게 이루어져서 발생
    - **루핑 해결책** : Maximum Hop Count를 이용 / (일정 홉 카운트 넘어가는 라우팅 경로는 unreachable로 간주하고, flush time이 지난 후에는 아예 라우팅 테이블에서 삭제)
    - 스플릿 호라이즌 : 라우팅 정보가 들어온 곳으로는 같은 정보를 내보낼 수 없다. 즉, 두 라우터 간의 루핑만을 막기 위해 만들어진 기술이다.
    - 라우트 포이즈닝, 포이즌 리버스, …

## IGRP 라우팅 프로토콜
- RIP와 같은 디스턴스 벡터 라우팅 프로토콜 중 하나. 시스코에서 만들어낸 프로토콜이라, 시스코 라우터에서만 사용 가능
    - 대역폭, 딜레이, Reliability, Load(부하), MTU(최대 전송 유닛 크기) 5가지를 보고 경로 선택을 하므로 홉 카운트만 가지고 목적지를 찾는 RIP보다는 좀 더 지능적으로 경로선택 가능

## OSPF 라우팅 프로토콜
- OSPF는 IP 패킷 안에 프로토콜 넘버 89로 들어가므로 이것만 봐도 OSPF 정보인 것을 알 수 있다.
    - 컨버전스 타임 : 라우터 간에 서로 변경된 정보를 주고받는 데 걸리는 시간. 즉, 어떤 인터페이스가 죽었을 때 이 정보가 모든 라우터들 사이에 퍼지는 시간이다. RIP는 매 30초마다 한 번씩 업데이트 일어나고 홀드다운 타임, 에이징 등으로 컨버전스에 많은 시간이 걸리지만, OSPF는 어떤 변화가 생길 때 바로 전달 가능하여 훨씬 빠르다.
    - VLSM을 지원한다. → IP 주소 효과적 사용 + 라우팅 테이블을 줄이는 효과
    - 네트워크 제한 → RIP는 최대 15개의 홉 카운트를 가지나, OSPF는 제한 없음
    - 경로 결정 → RIP는 홉 카운트만을 따짐, OSPF는 많은 관련 요소를 합쳐 경로를 선택하므로 훨씬 정확한 경로 선택이 가능

**Comment by jjangsungwon** [comment]
## RIP (Routing Information Protocol)
- 라우팅 프로토콜
- 다이내믹 프로토콜
- 내부용 라우팅 프로토콜
- 디스턴스 벡터 알고리즘
- 홉 카운트 (좋은 길을 결정하는 기준)
  - 최대한 갈 수 있는 홉 카운트의 거리: 15 (16개부터는 도착 불가) 
- 30초 (업데이트 주기)

### RIP 홉 카운트의 단점
- 경로 선택을 오로지 `홉 카운트에만` 의존하면 속도나 회선의 신뢰도, 회선의 로드 등을 확인해 볼 수 없다. 커다란 네트워크에서는 더 빠른 길을 찾지 못하는 경우가 빈번하게 발생한다.
- RIP는 15개 이상의 홉 카운트를 거쳐서 갈 수 있는 곳은 Unreachable(갈 수 없음)로 정의하고 데이터를 보내지 못하기 때문에 커다란 네트워크 상에서 사용하기는 무리가 있다. 

그럼에도 불루하고 아직도 많은 곳에서 RIP를 사용하는 이유는 다음과 같다.
- 소규모 네트워크 상에서는 효율성이 좋다.
- 라우터의 메모리를 적게 사용한다.
- 구성이 간편하다.
- 모든 라우터에서 지원하는 표준 라우팅 프로토콜이다.

## Distance-Vector 라우팅 알고리즘
- `시간`: 한 번 배운 라우팅 테이블을 계속 전달하기 때문에 업데이트가 모든 네트워크에 전달되는 시간(컨버전스 타임, Convergence Time)이 많이 걸린다 -> 루핑이 발생할 수 있다.
- 대책
  - Maximum Hop Count: 최대 홉 카운트를 정해놓으면 라우팅의 루핑이 발생하더라도 어느정도에 이르게 되면 멈출 수 있다. 그러나 요즘처럼 네트워크의 규모가 커질 경우 치명적인 약점을 드러내게 된다.
  - Hold Down Timer: Hold Down 타이머가 동작하고 있는 동안에는 외부에서 해당 네트워크에 대한 라우팅 경로 정보를 받았을 때 원래 가지고 있던 메트릭 값보다 큰 값이 들어오면 무시한다.
  - 스플릿 호라이즌(Split Horizon): 라우팅 정보가 들어온 곳으로는 같은 정보를 내보낼 수 없다. 두 라우터 간의 루핑만을 막기 위해서 만들어진 기출이라서 전체 라우터 네트워크의 루핑을 막기는 어려울 수 있다.
  - 라우트 포이즈닝(Route Poisoning): 다운된 네트워크를 무한대치로 바꾸어 버리는 방식이다. 
- 결론: 디스턴스 벡터 알고리즘은 쉽고, 간편하고, 라우팅 테이블을 적게 사용하는 등 여러 가지 장점이 있지만, 루핑이 발생하기 쉽다.

## IGRP 라우팅 프로토콜
- 라우팅 프로토콜
- 다이내믹 프로토콜
- 내부용 라우팅 프로토콜
- 모든 라우터에서 전부 사용 가능한 프로토콜 x
- Bandwidth, Delay, Reliability, Load, MTU 를 사용해서 경로 결정

## OSPF 라우팅 프로토콜
- 변화가 생기면 바로 전달 -> 실용적
- VLSM 지원
- 네트워크 크기 제한 x
- 경로 선택에 많은 정보 활용
- 링크스테이트 라우팅 알고리즘
- ...
