### ISSUE TITLE
12. IPv6로 떠나는 여행 

### ISSUE THREAD

**Issue by hhhyunwoo** [WhiteKow/hoony-easy-written-cisco-networking-study#9]

**Comment by hhhyunwoo** [comment]
## IPv6 의 필요성

- IPv4 주소의 주소공간 부족
    - IPv6는 IPv4 와 엄청난 양의 주소 차이가 남

### NAT

- Network Address Translation
- 내부에서는 Private IP 주소, 외부에서는 공인 IP 주소를 사용할 수 있게 하는 것

### Subnet

- 서브넷 마스크를 이용해서 네트워크를 잘게 쪼게서 사용하여 주소를 아낌

## IPv6의 주요 특징

- IP 주소 범위
    - 32 bit → 128 bit
- IP 주소의 자동 구성
    - Stateless Auto Configuration 를 사용하여 어떤 장비든 네트워크에 접속만 되면 자동으로 주소를 구성할 수 있음
- 보안
    - IPSec이 디폴트라서 어디서나 보안을 적용할 수 있음
- Mobility
    - 더 효과적이고 간편함
- 브로드캐스트
    - 브로드캐스트가 없어지고, 멀티캐스트가 그 역할을 대신 함
    - 브로드캐스트는 이전에 필요악이었음.
- 16진수를 사용함
    - 2001:0db8:010f:0001:0000:0000:0000:0d0c
- 브로드 캐스트가 사라지고 애니케스트가 생김
    - 아무나 제일 먼저 받는 녀석이 임자가 되는 형태

**Comment by ChanhuiSeok** [comment]
# IPv6

- IPv4 주소의 공간 부족으로 출현했다. 이론상 2^32(=약 43억) 만큼 주소를 만들 수 있는데 현실적으로 배정 가능한 IP 주소는 약 2억 5천만개 정도였다.
- 주소 부족 해결 방법
    - NAT(Network Address Translation) : 내부에선 Private 주소를 사용하고, 인터넷으로 나갈 때만 공인 IP 주소를 쓰게 되면 IP 주소가 몇 개 없어도 인터넷이 가능하다는 장점
    - 서브넷팅 : 네트워크를 잘게 쪼개 쓰는 것.
    - DHCP(Dynamic Host Configuration Protocol) : 안 쓰는 주소는 자동으로 회수하고, 주소가 필요한 PC에 그때그때 주소를 배분
    - CIDR(Classless Inter Domain Routing) : 클래스 A, B, C 등의 약속을 무시하고 뒤에 붙은 서브넷 마스크만 가지고 클래스를 지정

- IPv5도 있다. IPv5는 QoS 제공을 위한 실험적인 Resource Reservation Protocol 이다. 인터넷 등에서 디지털 사운드나 멀티미디어 데이터와 같은 리얼타임 데이터를 효과적으로 전송하기 위해 만들어진 프로토콜이며, IPv4와 공존하면서 상호작용하도록 디자인된 프로토콜이다.

## IPv6 무엇이 달라졌나

- 확 넓어진 주소 공간
    - 128비트 체계 (2^128), 거의 무한 개수만큼 가능한 공간임
    - Global Address : 주소 겹침 없이 전 세계적으로 유일한 주소를 마음 놓고 쓸 수 있다.
    - IP Header의 구조가 대폭 개선됨 : 헤더 정보를 간소화하고 효과적으로 배치해 라우팅 성능을 획기적으로 올림
    - 다양한 IPv4와의 호환 옵션 제공
- 넓은 주소 공간 덕분에 계층화된 주소 배정 가능
    - 128비트로 넓어져서 주소의 계층적 관리가 가능해졌고, 이러한 관리 기법으로 효과적인 주소 배치가 가능해졌다.
    - 여러 개의 네트워크를 하나의 네트워크로 묶어 트래픽을 줄일 수 있게 되었다.
- Aggregation
    - 한마디로, 묶는다는 의미. (Aggregation이 가능한 것은 계층적인 주소 배정이 가능해졌기 때문)
    - 왜 묶는가? ⇒ 간단하게 하기 위해서이다.
    Prefix Aggregation을 하는 이유는, 여러 개의 경로 정보를 하나로 묶어서 라우팅 테이블을 줄일 수 있고, 라우팅 테이블을 줄이면 라우터의 메모리 절약은 물론 라우팅을 훨씬 효과적이고 빠르게 진행할 수 있게 된다.
- Stateless Auto Configuration
    - 자동으로 호스트의 주소를 만들어 주며 IPv4에는 지원하지 않던 새로운 기능
    - 좀 더 자세히 호스트를 구성하려면 Stasteful Auto Configuration을 이용하며 대표적으로 DHCPv6이 있다.
- 브로드캐스트 대신 멀티캐스트
    - 브로드캐스트는 IPv4에서 대역폭을 많이 소비했다.
    - 하지만 IPv6에서는 멀티캐스트가 그 역할을 대신한다.
- 간단해진 헤더 정보
    - IPv4보다 헤더 정보가 절반으로 감소해서 패킷 처리가 빨라졌지만 주소 길이가 4배나 늘어나 주소 확인에는 문제가 있을 수 있다.
- 네트워크 Mobility가 좀 더 편리해지고, 효과적으로 수행이 될 수 있게 됨

**Comment by jjangsungwon** [comment]
### IPv6, 왜 필요한 걸까요?
- IPv4의 주소 공간 부족
- IPv4의 복잡한 헤더
- IPv4 주소 배정 방식 복잡, 체계적인 라우팅 정보 Aggregation 기능 불가, 효율적이지 못한 보안 기능과 Mobile IP
- ...

### IPv5는 없었는지?
- IPv5는 인터넷과 같은 곳에서 디지털 사운드나 멀티미디어 데이터와 같은 리얼타임 데이터를 효과적으로 전송하기 위해 만들어진 프로토콜이다.
- IPv5는 IPv4를 대체하기 위한 프로토콜이 아니라, IPv4와 공존하면서 작동하도록 설계되었다. 현재는 유사한 프로토콜들이 많이 나오면서 ㅈ쓰임새가 많이 줄었다.

### IPv6에서 달라진 점
- 넓어진 주소 공간 (32비트 체계 -> 128비트 체계)
  -  IPv4와는 비교할 수 없을 정도로 주소 공간이 넓어짐 
  - Gobal Reachability : 전 세계의 네트워크 어디에서나 주소를 변경하지 않고, 고유의 주소를 가지고 접속이 가능함
  - 넓어진 주소 공간으로 인해 주소의 계층화가 가능해짐 -> 수월한 주소 관리, 효과적인 주소 배치 -> 네트워크를 묶어 트래픽을 줄일 수 있음  
- 간편해진 IP 헤더
- 다양한 IPv4와의 호환 옵션
- Auto Configuration : 특정 서버가 없어도 라우터 등에서 자동으로 호스트의 IP 구성이 가능하게 해주는 방식
- 브로드캐스트가 사라짐 : 멀티캐스트가 대신 그 역할을 수행함. 기존의 IPv4와 달리 전달 범위 지정 가능
- Mobility : IPv4에서도 지원이 되던 IETF 표준이었지만, 여러가지 기능을 추가했어야 했음. IPv6에서는 Built-in 되어 있기 때문에 필요할 때마다 사용 가능함
